### ISSUE TITLE
DirectLine token is getting expired and I'm not able to generate a new one(using websocket)

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotFramework-DirectLineJS#101]
_From @prajwalsimha94 on October 21, 2018 15:16_

I'm using BotFramework DirectLine websocket to post and receive messages with the bot. While it works fine, the directline token expires in about half hour, forcing my app to generate a new token. I'm using the following code to subscribe to "Token Expired" event:

```
directline.connectionStatus$
.subscribe(function(connectionStatus)) {
  switch(connectionStatus){
    case BotChat.ConnectionStatus.Uninitialized:
      //some code
      break;
    case BotChat.ConnectionStatus.Connecting:
      //some code
      break;
    case BotChat.ConnectionStatus.Online:
      //some code
      break;
   case BotChat.ConnectionStatus.ExpiredToken:
      // generate a new token and reconnect to the conversation
      break;
  }
}

```
The problem is, case "BotChat.ConnectionStatus.ExpiredToken" is not getting triggered even if the token is expired. But while using the POLLING approach the expired token event gets triggered.

Browser console throws error 403 forbidden when I try to post an activity after the token is expired. Any help would be appreciated. Thanks!

_Copied from original issue: Microsoft/BotFramework-WebChat#1223_

**Comment by bhushanvadgave** [comment]
@vincec-msft 
We have enabled websocket in our webchat by doing a minor code changes in DirectlineJS dependency. Though "using watermark to fetch history messages" is working fine, we are facing THIS issue with ExpiredToken event. ExpiredToken event is not triggered when token actually gets expired..

Can you please guide us on this?

**Comment by carlosscastro** [comment]
Hello @bhushanvadgave and @prajwalsimha94!

To debug this efficiently, I would need exact repro steps. For example, start from sample "X", add code "Y", run command Z, deploy to FOO with steps XX and see the result.

From the information you sent, I'm not sure on how to get a repro of this. Could you please send me the repro steps? Also, the smaller the repro sample, the easier for me to debug.

Also, you mentioned "enabled web socket in our webchat by doing a minor change in direclinejs dependency". If these could be affecting the token renewal, we'll need to know exactly what you changed, otherwise there is no way we can know what is going on.

Please provide the 2 pieces of information and we'll investigate (repro steps and change you did in DirectlineJs). 

Thanks!

**Comment by carlosscastro** [comment]
@compulim and @ckkashyap we might need to debug this issue together once we get the requested info.

**Comment by carlosscastro** [comment]
Hello @bhushanvadgave and @prajwalsimha94! For now, what I see the steps are

- Create a bot
- Enlist in directline js
- Send messages to your bot and receive nmessages (verify that this works)
- Stop interacting with the bot for 30 minutes to wait for token expiration
- Bug: After 30 minutes talk to the bot and get a 403 plus the BotChat.ConnectionStatus.ExpiredToken event never triggers.

*Does that sound accurate? If that is accurate, then we only need to know what you changed in direcline js.*

**Comment by bhushanvadgave** [comment]
@carlosscastro You are right with the above steps.

Below is the only change we did in botframework-directlinejs dependency of Webchat

File src/directLine.ts
![image](https://user-images.githubusercontent.com/3713053/48830723-45b4f100-ed9b-11e8-8d67-8a3bc46f945a.png)

**Comment by Anandks1993** [comment]
Hey guys, for me after 30 minutes, I am getting reply message from bot. ExpiredToken status is not triggered after 30 minutes

**Comment by bhushanvadgave** [comment]
@carlosscastro Do you have any update on this issue? I hope I have shared all the information that you need to reproduce this issue.

**Comment by compulim** [comment]
Tracking this issue on #124 (uber-bug on "resume conversation story").

**Comment by xtianus79** [comment]
@compulim this is still an issue
