### ISSUE TITLE
When is it safe to let a user click retry on a failed message...

### ISSUE THREAD

**Issue by watadarkstar** [Microsoft/BotFramework-DirectLineJS#105]
```javascript
directLine.postActivity(giftedMessageToBotMessage(newMessage)).subscribe(
    id => {
      if (id === "retry") {
        // 1. Is it safe to let the user click retry on the failed message?
      }
   },
   error => {
      // 2. Is it safe to let the user click retry on the failed message? 
    }
)
```

In the above cases when is it safe to let the user click retry on the message (activity) to re-attempt to send it? 

If I let the user click retry and the message has not actually failed then the consequence is that the bot might send two messages back to the user when it sees message 1 and message 2 come in where message 2 is a retry of message 1.

Does directline automatically retry to send the message or should we?

(See 1 and 2 in the code above)

Version:
`"botframework-directlinejs": "^0.9.17",`

Any help is appreciated.

**Comment by compulim** [comment]
DirectLineJS do not retry sending the message and our platform do not dedupe message.

If you need idempotency for messages, you can use `channelData` and put a pseudo ID on the DirectLineJS (client side). And the bot (server side) can use the pseudo ID to manage duplicates.

**Comment by watadarkstar** [comment]
Thanks for the response @compulim. For what its worth, I actually ended up deduping messages on the client side. If a message came in and it was the same one I have seen before I wouldn't add it to the UI. I couldn't get server-side deduping to work because it's hard to tell if the client is retrying and therefore the message should not be deduped.
