### ISSUE TITLE
Direct Line does not work on Node.js based on current instructions

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/BotFramework-DirectLineJS#107]
[#L549](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L549) contains a reference to a WebAPI-only constructors `FormData` and `Blob` which are not present in Node. This yields the error: `ReferenceError: FormData is not defined`. or `ReferenceError: Blob is not defined`.

The current README does not adequately describe the steps needed to use DirectLine in a Node app. Primarily the requirement for polyfills attached to the `global` object for both `Blob` and `FormData`.

**Comment by watadarkstar** [comment]
Hi @justinwilaby this library is not meant to be used within node. It's a client library used on the client side (browser). Can I ask why would you want to use this library on the server side?

**Comment by billba** [comment]
We've had a few people use this with Node, usually for proxy work like making Alexa work with Bot Framework bots via Direct Line.

@justinwilaby I believe there are polyfills out there for `FormData` and `Blob` which should let you use DLJS with Node.

**Comment by watadarkstar** [comment]
Oh right on that makes sense!

**Comment by justinwilaby** [comment]
I suppose I missed communicating the primary reason for filing this ticket so I apologize for not being more specific. I've updated the title and original description for better clarity.

**Comment by compulim** [comment]
The work is being tracked at #84 and #85.

**Comment by kushalbhabra** [comment]
Hi, I'm using DirectLine JS 0.14.1 and trying to send attachment but getting an error from the library.

```
ReferenceError: FormData is not defined
    at MergeMapSubscriber.project (C:\Users\Kushal\Documents\code\nodejs-azure\b\smpls\samples\javascript_nodejs\13.core-bot\node_modules\botframework-directlinejs\lib\directLine.js:518:9)
```

I've also added below two lines in my application
```
global.XMLHttpRequest = require('xhr2');
global.WebSocket = require('ws');
```

Is there anything else to be done so that formdata and blob don't fail?
