### ISSUE TITLE
An exception happened occasionally.

### ISSUE THREAD

**Issue by zhou-xinghai** [Microsoft/BotFramework-DirectLineJS#11]
Hi, I use this JS in backend server to connect bot framework in the websocket way. 
But occasionally (once per day usually) it thorws the error as below and as along as it happends ,the postActivity function will always throw this error. Is it a bug or something I did wrong? 
![image](https://cloud.githubusercontent.com/assets/8207172/23733401/a520b66a-04b3-11e7-9d71-dfdb721d535c.png)

**Comment by billba** [comment]
Please upgrade to the latest release; `Observable.throw` was not included but now it is.

This may solve one problem and reveal another, but let's take this one step at a time.

**Comment by zhou-xinghai** [comment]
okay, thanks you, have upgraded to the latest one.

**Comment by zhou-xinghai** [comment]
hi, sometimes when i call postActivity, it returns with the id "retry". It seems a problem of directline that when I send msg to directline it returns retry rather than consiation|id like "BwWr2WLPs6a2LaalX4abzC|0000001". Do you have any idea on how it happens? thanks

**Comment by billba** [comment]
That means the call failed but could be retried. I admit this is a poor API choice, will look at cleaning up.

**Comment by zhou-xinghai** [comment]
Is this error return by directline API? Is there way to start a new conversation under this condition or how can I handle this error with BotFramework-DirectLineJS ? Any suggestion is appreciated.

**Comment by billba** [comment]
This return value means the attempt to post the activity failed, possibly due to timeout or other network conditions. The conversation is still ongoing and doesn't need to be restarted.

**Comment by zhou-xinghai** [comment]
Yes, but it seems not a network problem. As long as i restart the service which will start a new conversition then it goes fine again. I guess i need to log out the error msg to find the real cause.

**Comment by billba** [comment]
My mistake, I responded from memory without looking at the code.

When `postActivity` returns `"retry"` it means the access token has expired. If you `subscribe` to `connectionStatus$` as [described](https://github.com/microsoft/botframework-directlinejs#monitor-connection-status) in the README you can see it changed to `ExpiredToken`.

A token is a short-lived credential you get by calling the `tokens/generate` Direct Line endpoint. The only reason to use a token is when you don't want to expose a secret to the outside world, usually in a web page. This isn't a problem on a server. On a server, you probably shouldn't be using tokens. You can just use the Direct Line secret.

Even if you have a reason to use a token on the server, DirectLineJS renews the token every 15 minutes by calling the `/tokens/refresh` DirectLine endpoint. So if you are getting this error:

* You are having an extended connectivity problem (one that lasts more than 15 minute), or
* You are creating DirectLineJS by passing the token using the `secret` parameter, which will not trigger the token renewal process

If you are in fact not using tokens, then there is probably a bug in my code.

**Comment by zhou-xinghai** [comment]
Thanks for your clue. I use secret to create the directline instance. The problem occurs when it runs more than 15 hours last time. I added some log in your function catchPostError and catchExpiredToken to track what error may cause the problem. It has run more than 7 hours normally. I'll let you know if I reproduce it.

**Comment by billba** [comment]
That sounds frustrating. I'm out of ideas for now. This could be a bug in the library (e.g. a memory leak, since it only happens after many hours) or a problem with Direct Line itself. I look forward to hearing what you learn.

**Comment by billba** [comment]
update: I was dort of right the first time. That error can mean token issues OR a variety of other errors, including timeout and connectivity errors.

**Comment by zhou-xinghai** [comment]
I haven't reproduce the issue yet. It goes fine in these two days, will keep you update.

**Comment by zhou-xinghai** [comment]
Hi billba,
  I reproduce the issue. It happed when the websocket lost connection, then you will reconnect the websocket immediately. Then after a while when I post msg to directline, it return 403 and the msg "error": {\r\n    "code": "TokenExpired",\r\n    "message": "Token has expired"\r\n  }\r". Then all the subsequent calls will return the same.
I guess the problem is caused by function reconnectToConversation(). You reset the token here which make my secret don't work any more. I read the doc of directline and didn't find any infomation on that. So is it necessary to set that value to replace the secrect?

**Comment by billba** [comment]
Ah! You found a bug. We should not be setting `this.token` unless it was already set. I will fix in the morning. Very sorry for the trouble, thanks for investigating.

**Comment by billba** [comment]
Please update to the latest version. Thanks again for tracking this down.

**Comment by zhou-xinghai** [comment]
Okay, thank you .
