### ISSUE TITLE
Error: Observable_1.Observable.throw is not a function

### ISSUE THREAD

**Issue by hpavenge** [Microsoft/BotFramework-DirectLineJS#113]
ERROR TypeError: Observable_1.Observable.throw is not a function
    at DirectLine.push../node_modules/botframework-directlinejs/built/directLine.js.DirectLine.catchExpiredToken (directLine.js:332)
    at CatchSubscriber.selector (directLine.js:278)

Chat used to work but updating to the latest version of RXJS caused some issues.

**Comment by mitulgolakiya** [comment]
@hpavenge any update on this?

**Comment by compulim** [comment]
This is an issue on one of our dependency `redux-observable`, referring to an unsupported version of RxJS (instead of 5, it use 6).

We have details about the issue over here, https://github.com/Microsoft/BotFramework-WebChat/issues/1146#issuecomment-435483963.
