### ISSUE TITLE
403 error when sending a file as attachment

### ISSUE THREAD

**Issue by Sams4u** [microsoft/BotFramework-DirectLineJS#114]
I am trying to send a file as attachment using the directline js. Even if i try to send the attachment by url i believe directline js automatically converts it into blob and send the same attachment by upload. But this is failing. Its throwing 403 error.
`Access to XMLHttpRequest at 'https://directline.botframework.com/v3/directline/conversations/C9hQ9cWJENY6YHW2kHAUtr/upload?userId=XXXXX' from origin 'https://xxxxxx.azurewebsites.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

```
curl "https://directline.botframework.com/v3/directline/conversations/C9hQ9cWJENY6YHW2kHAUtr/upload?userId=xxxx" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" -H "Referer: https://xxxxx.azurewebsites.net/test/index.html" -H "Origin: https://xxxxxx.azurewebsites.net" -H "X-Requested-With: XMLHttpRequest" -H "Authorization: Bearer 5J6eDAGa7wY.dAA.QwA5AGgAUQA5AGMAVwBKAEUATgBZADYAWQBIAFcAMgBrAEgAQQBVAHQAcgA.40jFMiqD1AE.HTPhZyktSRY.Akh-9W9mXAvAmIJO6O2CZQJfbbpmePxjJnwb8sYH7xQ" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryVWvBKEwlVb0M85E9" --data-binary ^"------WebKitFormBoundaryVWvBKEwlVb0M85E9^

Content-Disposition: form-data; name=^\^"activity^\^"; filename=^\^"blob^\^"^

Content-Type: application/vnd.microsoft.activity^

^

^{^\^"from^\^":^{^\^"id^\^":^\^"XXXXXX^\^",^\^"name^\^":^\^"XYZ^\^"^},^\^"type^\^":^\^"message^\^",^\^"text^\^":^\^"msg^\^"^}^

------WebKitFormBoundaryVWvBKEwlVb0M85E9^

Content-Disposition: form-data; name=^\^"file^\^"; filename=^\^"test process.jpg^\^"^

Content-Type: image/png^

^

^PNG^

^^

^
```

**Comment by compulim** [comment]
Looks like there may have been a glitch on our platform. I have just verified it is working now.

Is the problem still persists right now?

**Comment by kishkumk** [comment]
I having the same issue which still persist. I'm using directline.js file got from "https://unpkg.com/botframework-directlinejs@0.10.0/directLine.js". Using the above js file,its throwing 403 error and CORS issue as above while sending attachments. Also when I'm trying to send OBJECT through activity property "value", its getting failed. Its not receiving at bot end. Is there any updated js file for directline.

**Comment by cwhitten** [comment]
This was caused due to intermittent service degradation in December 2018. Closing. Please re-open if the issue persists.

**Comment by febineldhose** [comment]
i can't attach files,when i am trying attach some file it always trigger 'retry' as response, can you help me to resolve this.
