### ISSUE TITLE
Directline Token Secret - Hide from Javascript

### ISSUE THREAD

**Issue by kesavanpurushothaman** [Microsoft/BotFramework-DirectLineJS#117]
Hi Team,

I am using Directline.js for enabling Webchat in our ASP.NET CORE web site.
We wanted to hide the secret from HTML.

BotChat.App({
            directLine: {  secret: '@Model.Token' },
            user: { id: '@Model.UserId', name : '@Model.Name' },
            bot: { id: 'botid' },
            resize: 'detect',
        }, document.getElementById("BotChatGoesHere"));

Thanks, Kesavan Purushothaman

**Comment by EricDahlvang** [comment]
Hi @kesavanpurushothaman 

The Secret can be exchanged for a temporary Token.  Please see here for an MVC example: https://github.com/EricDahlvang/TokenBotExample/blob/master/TokenBotExample/Areas/Bot/Models/WebChatModel.cs
