### ISSUE TITLE
Resume conversation after call botConnection.end() 

### ISSUE THREAD

**Issue by rainmakerho** [Microsoft/BotFramework-DirectLineJS#118]
I use "samples/backchannel/index.html" to test stop/start conversation.
How to resume conversation after call botConnection.end() ?
Thanks.

**Comment by compulim** [comment]
Transferring this one from Web Chat to DirectLineJS.

**Comment by compulim** [comment]
Marking as dupe of #124 and resolving it over that uber-bug.
