### ISSUE TITLE
ws.onerror

### ISSUE THREAD

**Issue by vasilkrastev90** [Microsoft/BotFramework-DirectLineJS#12]
Hi,

I was wondering is there any reason why there is no onerror method on the observable websocket. I am also using BotFramework-Webchat and I am wondering if there is any recovery planned for if the socket fails.

I see this code in the Chat.tsx file of the Webchat

this.activitySubscription = botConnection.activity$.subscribe(
            activity => this.handleIncomingActivity(activity),
            error => konsole.log("activity$ error", error)
        );

Which means that even if there is an error on the socket and I would like to create a new one I will need to update the activity subscription in the Chat.

Is there a recovery mechanism in place that I am missing?  

The issue is mostly about the error recovery in the client webscoket I guess once this is resolved I can update the webchat accordingly. Hence opening the issue here.

Thanks

**Comment by billba** [comment]
The internal method `observableWebSocket` does throw errors. `activity$` calls `webSocketActivity$`, which catches those errors and repeatedly attempts to reconnect to the webSocket.

Basically DirectLineJS handles every error condition as well as possible, and so if `activity$` throws an error it means it has tried everything repeatedly, and nothing worked.

In the case of WebChat, we have a plan to have the UX reflect this state, but that code is not in place and so we don't handle the error right now. I admit that this is not ideal, but the new code is coming soon!

**Comment by vasilkrastev90** [comment]
Thanks for your response Bill.

I have played around with RX (https://jsfiddle.net/gk6se537/) and my understanding is that if there is some error caused by abnormal socket termination (as actually specified in code comments) then the retryWhen will cause the whole sequence to execute again. This means that a upon a successful recovery a new socket will be created. It should also seamlessly recover all messages possibly missed due to the error.

However a question that remains unanswered for me is that it seems that if the socket creation fails for some reason this error is not handled. i.e. ( https://jsfiddle.net/x2gnzv2y/ ) Am I missing something here?

**Comment by billba** [comment]
If `WebSocket` fails on creation it doesn't throw an error, it just calls `onClose`.
