### ISSUE TITLE
error : Invalid token or secret ,when trying to refresh token or resuming conversation  after token expiration by passing conversationId to Conversations Api

### ISSUE THREAD

**Issue by utkarsh24** [microsoft/BotFramework-DirectLineJS#134]
Hello,
I am working on questionnaire bot , who ask users questions predefined by the system.
I am using token to create directline instance,

I have scenario where user can left the conversation and get back to it latter, may be same day or other day.

To resume conversation i am saving conversationId and token generated when starting new conversation to CosmosDB

I am calling **https://directline.botframework.com/v3/directline/conversations/{conversationId}** and passing the token i have saved to CosmosDB
but i get **Invalid secret or token** Error 
I have also tried to get refreshed token by calling **https://directline.botframework.com/v3/directline/tokens/refresh** by passing the token i have saved but also get the same error.

Could you please help me to get the token with the same conversationId so that i can use it to resume my older conversation.

**Comment by utkarsh24** [comment]
Any update on this?

**Comment by utkarsh24** [comment]
@billba,@Jeffders could you please look in to this issue.

**Comment by utkarsh24** [comment]
Any updates?

**Comment by cwhitten** [comment]
Hello @utkarsh24 are you using the DirectLineJS library or hitting the DirectLine service directly?

**Comment by utkarsh24** [comment]
Hello @cwhitten,

I am using WebChat.js as bot client.
I store conversationId and token when the conversation starts.

following is my code..

```
if (this.conversationId) {
        console.log("In resume");
        console.log("getting convesation")
        let converstion =  -- server api to get conversation token using existing token created while creating new conversation (uses https://directline.botframework.com/v3/directline/conversations/{conversationId} api to get token)
        var botConnection = new BotChat.DirectLine({
          token: converstion.token,
          streamUrl: converstion.streamUrl,
          conversationId: converstion.conversationId,
          domain: domain
        });
        BotChat.App({
          botConnection: botConnection,

          user: { id: 'dl_' + params['id'], name: '' },
          bot: { id: 'botid' },

        }, document.getElementById("bot"));
        botConnection
          .postActivity({
            from: { id: 'dl_' + params['id'], name: 'username' },
            name: 'postLocationData',
            type: 'Resume',
            value: 'Hi'
          })
          .subscribe(function (id) {
            console.log('"Resume::Greetings request event" sent');
          });
      }
      else {
        let token = -- server call to get new token(uses https://directline.botframework.com/v3/directline/tokens/generate api to create new token));
        console.log(token);
        let secret = token.token;
        console.log("In new conversation");
        var user = {
          id: 'dl_' + params['id'],
          name: 'one'
        };

        var newBotConnection = new BotChat.DirectLine({
          token: secret,
          domain: domain,
          user: user
        });
        BotChat.App({
          botConnection: newBotConnection,

          user: user,
          bot: { id: 'botid' },
          resize: 'detect'
        }, document.getElementById("bot"));
        newBotConnection
          .postActivity({
            from: user,
            name: 'requestWelcomeDialog',
            type: 'event',
            value: ''
          })
          .subscribe(function (id) {
            console.log('"Greetings request event" sent');
          });
       }
    }
```
Everything works fine untill token expires.
When token got expired and i make call to https://directline.botframework.com/v3/directline/conversations/{conversationId} using stored conversationId and token it throws an error--> Invalid token or secret

**Comment by cwhitten** [comment]
This is currently working as designed - if you allow the token to expire you need to regenerate the token.
