### ISSUE TITLE
Documentation around suggestedActions

### ISSUE THREAD

**Issue by gilesbutler** [Microsoft/BotFramework-DirectLineJS#15]
In the release notes for `0.9.4` it mentions "adds support for `suggestedActions` in messages"

Is there any documentation around what this is and how to implement it?

I couldn't find any info about `suggestedActions` in the main Bot Framework documentation.

Thanks

**Comment by billba** [comment]
This feature is still under development. First support was added here, then in [today's release](https://github.com/Microsoft/BotFramework-WebChat/releases/tag/v0.10.4) of WebChat. Look for bot SDK support from BotBuilder coming soon!

**Comment by gilesbutler** [comment]
Awesome, thanks @billba 👍
