### ISSUE TITLE
Error in console (Refused to set unsafe header "User-Agent")

### ISSUE THREAD

**Issue by crutkowski-84** [Microsoft/BotFramework-DirectLineJS#152]
Appears to be caused by the updates in Pull Request #148.

The console error appears whenever a message is sent from the client to the bot.  I am using 64 bit Chrome, Version 71.0.3578.98, on Windows 10.

**Comment by cwhitten** [comment]
Hello @crutkowski-84. We are aware and in the process of addressing this. It is technically a warning (that looks like an error). We'll update this GH issue as we make progress.

**Comment by cwhitten** [comment]
This addressed in https://github.com/Microsoft/BotFramework-DirectLineJS/pull/153 and available in `0.11.1` of the library
