### ISSUE TITLE
Client cannot catch Post error Callback

### ISSUE THREAD

**Issue by Keyan-Wang** [microsoft/BotFramework-DirectLineJS#166]
This is our client code, we found we do not catch error Callback.

    sendPostBack(text, value, from, successCallback, errorCallback) {
      this.botConnection
         .postActivity({
          type: 'event',
          text,
          value,
          from
        })
       .subscribe(
          id => {
            if (successCallback) {
              Logger.trackEvent('Chat_PostActivityCompleted', {
                message: `Send ${text} to server succeed.`,
                supportCaseId: this.props.supportCase.id
            });
            successCallback(id);
          }
        },
        error => {
          if (errorCallback) {
            errorCallback(error);
            Logger.trackEvent('Chat_PostActivityError', {
                message: `Send ${text} to server failed.`,
                supportCaseId: this.props.supportCase.id
            });
          }
        }
      );

our team member has already consulted about error handling mechanism when calling Post Activity, 
and turns out Direct line handling HTTP 4xx or 5xx code, and sending the client a 502. 
(https://github.com/Microsoft/BotBuilder/issues/2201)
What we want is handling 4xx or 5xx code by ourselves, and we had already have some change on source code, 

    private catchPostError(error: any) {
        if (error.status === 403)
            this. expiredToken();
        else if (error.status >= 400 && error.status <= 502)
        {
            return Observable.throw(error);
        }
        return Observable.of("retry");
    }

can you see if this is workable? Or do you have other alternatives and solutions?

**Comment by cwhitten** [comment]
@stevkan can you take a look at this one?

**Comment by cleemullins** [comment]
@Keyan-Wang It looks like this slipped through our daily triage process. Were you able to get resolution on this? If not, I'll close this out next week.

**Comment by Keyan-Wang** [comment]
yes,  I've solved it~ please close it. Thanks. @cleemullins

**Comment by pavan-kumar-js** [comment]
@keyanMalfoy How did you solve this?
@cleemullins Need help with this issue, we want to capture 502 and log it on our end
