### ISSUE TITLE
IE 11 compatibility with customized domain

### ISSUE THREAD

**Issue by jacyuan** [microsoft/BotFramework-DirectLineJS#174]
Hello,

**Concerned version**
- BotFramework WebChat : v0.14.0
- BotFramework DirectLineJS : 0.9.15

**Issues**
I would like to run some local tests with my local server. So I built my directLine instance with a specified "domain" (set to the domain property).
```
   var connector = new BotChat.DirectLine({
        webSocket: false,
        domain: "http://" + document.location.hostname + ":3000/directline",
        secret: "xxxxx" // with a specified domain, I don't think it's useful to set secret here
    });
```
The same code works under chrome and IE edge, but only works under IE11 when the debug mode is activated. (I read that it's often caused by using "console" in the code, so I replace manually all console that I found in my library (just for test), but nothing changes.)

When tracing with Fiddler for I/O http request, I found that, under chrome or IE edge, http calls are sent frequently to the backend server specified by domain (since websocket is set to false). But under IE11, this is not the case, after some init http calls, no more http polling is sent from IE11.

The strange thing is that, when I compared with another implementation which works under IE11,
the only difference is that:
the directline instance used under this implementation, no custom domain is specified, but only built with a simple secret property
```
 var connector = new BotChat.DirectLine({
        secret: "xxxxx" 
    });
```

Any suggestion on this please ? Thanks.

**Comment by cwhitten** [comment]
Hello @jacyuan - can you please update to the latest version of Web Chat and see if your issue still exists? Thanks.
