### ISSUE TITLE
Getting subscribed to multiple activities even though bot sends one.

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/BotFramework-DirectLineJS#175]
I am using following piece of code to subscribe for activities sent by bot.

```
directLine.activity$
.filter(activity => activity.type === 'message' && activity.from.id === 'yourBotHandle')
.subscribe(
    message => console.log("received message ", message)
  Promise.resolve(message);   // This line gets message more than 4 times even thought bot has replied once.
);
```

Using following to post a message to bot via direct line.

```
[directLine.postActivity({
        from: {
            id: 'bob'
        },
        // user: { id: 'bob'},
        text: input,
        type: 'message'
    }).subscribe((id) => console.log('SDK Posted activity, assigned ID ', id), (error) => console.log('Error posting activity', error));](url)
```

The problem here is, bot (that I am using with direct line connection ) is sending one reply but, in the subscribe method I get it almost 6 times. AND it is same activity object. I verified bot is actually sending only 1 reply.  

I am wondering is I am missing anything here while using this api.

**Comment by EricDahlvang** [comment]
@rjgmail88 Are those conversationUpdate events?  What kind of messages are they?

**Comment by rjgmail88** [comment]
I believe I am filtering to get only for message activity type. 

```
activity.type === 'message'
```

**Comment by sagarmodhavaniya** [comment]
i have same issues the same activity are i can get 
`directLine.activity$
.filter(activity => activity.type === 'message' && activity.from.id === 'yourBotHandle')
.subscribe(
    message => console.log("received message ", message)

);`
the two copy of messages object are received but i send only one

**Comment by sagarmodhavaniya** [comment]
i am also getting same problem

**Comment by naveenwinsome** [comment]
Hi,
Even I'm having the same issue. Are we still expecting the resolution for this?

**Comment by sagarmodhavaniya** [comment]
issue are solved 
it is so simple in your code your doing the multiple time subscribed the activity so you received activity

**Comment by naveenwinsome** [comment]
Hi Sagar,
Thanks. Can you please update the working code.

**Comment by vishwadeepghimirezph** [comment]
Hello @sagarmodhavaniya and @naveenwinsome,  is there any solution on this ? I am also facing same problem.

**Comment by sagarmodhavaniya** [comment]
@vishwadeepghimirezph  sure 

`directLine.activity$
.filter(activity => activity.type === 'message' && activity.from.id === 'yourBotHandle')
.subscribe(
message => console.log("received message ", message)
)`

**filter(activity => activity.type === 'message' && activity.from.id === 'yourBotHandle') is help to filter your activity**  
and one more thing you need to take care is the **subscribe** only ones at a time so if you do multiple subscribe then you received multiple activity 
Thank You !

**Comment by vishwadeepghimirezph** [comment]
> 
> 
> @vishwadeepghimirezph sure
> 
> `directLine.activity$ .filter(activity => activity.type === 'message' && activity.from.id === 'yourBotHandle') .subscribe( message => console.log("received message ", message) )`
> 
> **filter(activity => activity.type === 'message' && activity.from.id === 'yourBotHandle') is help to filter your activity**
> and one more thing you need to take care is the **subscribe** only ones at a time so if you do multiple subscribe then you received multiple activity
> Thank You !

Thank you for your reply @sagarmodhavaniya .
I already have above code as you have mentioned. But that also not working as expected. Also, in my code there is only one subscription not multiple.
Thank you.

**Comment by sagarmodhavaniya** [comment]
@vishwadeepghimirezph  can you shrare you code here ?

**Comment by vishwadeepghimirezph** [comment]
@sagarmodhavaniya Thank you for your reply. Below is my code. Thank you.
```
  // Create directlint object for connection
  const directline = new DirectLine({
    secret: directline_Secret_key  });
 
 
 // To post query
 directline.postActivity({
      from: {
        id: 'user',
        name: 'User',
       }
    })
      .subscribe(
        id => {
         
          console.log("QueryId", id)
          
        },
        error => {
          console.log("Error", error)
        }
      );
  };

 
  /* Listen to activities sent from the bot */
    directline.activity$
      .filter(activity => activity.type === 'message' && activity.from.id === botId)
      .subscribe(message => {
        if (message) {
          console.log("Reply", message)
        }
    });
  

```

**Comment by sagarmodhavaniya** [comment]
@vishwadeepghimirezph  looks like code is right  
please ones check your bot is sending message ones otherwise code is right as I see

**Comment by cwhitten** [comment]
Closing.
