### ISSUE TITLE
postactivity event to DirectlineJS is bringing back earlier received messages again

### ISSUE THREAD

**Issue by sanoorvishwa** [microsoft/BotFramework-DirectLineJS#179]
Hi There,
I have a problem related to DirectlineJS response when I post an event to DirectlineJS.

```
       botConnection = window.WebChat.createDirectLine({
            token: tokenCookie,
            webSocket: true
        });

       botConnection.postActivity({
            type: "event",
            value: value,
            from: user,
            name: "hostContexData"
        }).subscribe(function (id) {
            return console.log("Success --> userId = " + id);
        });
```

For the event I posted, my MS bot doesn't create any reply. However, I get reply from DirectlineJS that are previous 2-3 message. These message have already processed. So, I see duplicate messages in my Webchat.  Can anybody help me here?

Thanks,
Vishwa

**Comment by vincec-msft** [comment]
@compulim , since createDirectLine doesn't pass a watermark through to DirectLineOptions all previous activities will be retrieved. Webchat would have to expose the watermark option in the call to createDirectLine and pass it through to the DL constructor.

**Comment by compulim** [comment]
Web Chat v4 no longer taking in DLJS options and create DLJS object to use. Instead, it ask for the user to create DLJS and pass the object to Web Chat v4 to use.

The calling pattern is like this:

```js
window.WebChat.renderWebChat({
  directLine: window.WebChat.createDirectLine({
    token, watermark, ...
  })
});
```

@sanoorvishwa For the duplicated message, do you mean messages from the user? Direct Line channel is designed to echo back what the user just sent.

**Comment by stevkan** [comment]
Closing due to lack of response. If you continue to have related problems, please feel free to re-open this issue and post a new message.
