### ISSUE TITLE
Unable to pass custom properties in DirectLine API activity post C#

### ISSUE THREAD

**Issue by JitBanerjee** [microsoft/BotFramework-DirectLineJS#181]
**Requirement** : In our project we need to pass Activity object using C# in DirectLine API. With other property along with from , text ,type we want to pass "Properties" as well.

Error: Without passing own property it is working fine. But when we are assigning "Properties" parameter in Activity object below exception we are getting during execution of calling method. (From which method we are filling activity and calling API). Although "Properties" is a set property as well.

"Method not found: 'Void Microsoft.Bot.Connector.DirectLine.Activity.set_Properties(Newtonsoft.Json.Linq.JObject)".

DLL Info : We are using Microsoft.Bot.Connector.DirectLine 3.0.2 DLL to call the DirectLine Api.

![Activity](https://user-images.githubusercontent.com/37118374/57922204-b2163600-788e-11e9-959b-f32d1cddae3a.JPG)

Please suggest how we can pass our own property in Activity object. Thanks in advance.

**Comment by anusharavindrar** [comment]
You will need to pass the custom properties in Activity.channelData. As channelData is for additional data that is related to that specific message. You can refer to these links below to pass custom properties in DirectLine:

- https://github.com/Microsoft/BotFramework-WebChat/issues/721
- https://github.com/Microsoft/BotFramework-WebChat/issues/395
- https://github.com/microsoft/botframework-sdk/issues/3483

Hope this helps.

**Comment by anusharavindrar** [comment]
Were you able to pass the custom properties in Activity.channelData?

**Comment by anusharavindrar** [comment]
Closing the issue assuming its resolved.

**Comment by JitBanerjee** [comment]
sorry for delay reply anusharavindrar. Implemented using channelData and it is working as expected. thanks for your support.
