### ISSUE TITLE
RXJS version 

### ISSUE THREAD

**Issue by abyThinker** [microsoft/BotFramework-DirectLineJS#182]
Am working  witth angular 7 rxjs version 6.3 but directlinejs is giving error . how can i update rxjs version in directline

**Comment by shivamrajvir** [comment]
I have the same error, stuck with angular 5, cannot update it due to RxJS 5, as Angular 6 and above has RxJS 6+, and rxjs-compat doesnt work as there are breaking changes in Directline for RxJS 5

**Comment by poul-kg** [comment]
I have the same issue, I found npm package `botframework-directline-angular6` which works with angular 6, but not with angular 7.

And we already have angular 8 coming soon.

We need compatibility with Angular 7, 8, etc...

**Comment by harshithkashyap** [comment]
I have filed a PR for this at https://github.com/microsoft/BotFramework-DirectLineJS/pull/102
You can test this out with `npm i botframework-directlinejs-tmp@1.0.5`. We are using this with Angular 7.

**Comment by Sachinists** [comment]
I also had the same issue and I ran the below command and it worked for me.

**npm install --save rxjs-compat**

**Comment by cwhitten** [comment]
Hello. We have no plans to move to newer versions of RxJS. We'd actually prefer to remove the dependency from this library altogether as part of a new major release. Closing this particular issue as a won't-do

**Comment by orgads** [comment]
Do you have a planned schedule for removing this dependency?

**Comment by orgads** [comment]
@cwhitten / @compulim Ping 👆🏻
