### ISSUE TITLE
Ability to send "From Properties" when Directline is Init'ed  

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/BotFramework-DirectLineJS#184]
Feature Request

```typescript
directLine.postActivity({
    from: { id: 'myUserId', name: 'myUserName' }, // required (from.name is optional)
    type: 'message',
    text: 'a message for you, Rudy'
}).subscribe(
    id => console.log("Posted activity, assigned ID ", id),
    error => console.log("Error posting activity", error)
);
```
the From properties are only received when the user sends the first message.. if the same provision is added when the user connects to the bot 

```typescript 
var directLine = new DirectLine({
    secret: /* put your Direct Line secret here */,
    token: /* or put your Direct Line token here (supply secret OR token, not both) */,
    domain: /* optional: if you are not using the default Direct Line endpoint, e.g. if you are using a region-specific endpoint, put its full URL here */
    webSocket: /* optional: false if you want to use polling GET to receive messages. Defaults to true (use WebSocket). */,
    pollingInterval: /* optional: set polling interval in milliseconds. Default to 1000 */,
});
```

This would add features such as 

- greet the user by their name when they connect the bot 
- send proactive messages to the user when they are connected 
- greet the user based on time of day, such as good morning, good evening, etc

**Comment by tdurnford** [comment]
You can send a backchannel event from DirectLineJs to the bot with custom data in the activity's value property when the connection is established. See the code snippets below.

**DirectLine**
```javascript
import { DirectLine, ConnectionStatus } from 'botframework-directlinejs';
 
var directLine = new DirectLine({
    secret: '<DIRECTLINE_SECRET',
});

directLine.activity$
.filter(({ from }) => from.role === 'bot')
.subscribe(
    activity => console.log("received activity ", activity)
);
 
directLine.connectionStatus$
.subscribe(connectionStatus => {
    switch(connectionStatus) {
        case ConnectionStatus.Online:
          directLine.postActivity({
              from: { id: 'myUserId', name: 'myUserName' },
              type: 'event',
              name: 'webchat/join',
              value: { locale: 'en-US' }
          }).subscribe(
              id => console.log("Posted welcome event, assigned ID ", id),
              error => console.log("Error posting activity", error)
          );
          break;
    }
});
```

**Bot - Node SDK**
```javascript
this.onEvent(async (context, next) => {
    if (context.activity.name === 'webchat/join') {
        await context.sendActivity({ text: `Welcome to Web Chat! Your locale is set to ${context.activity.value}`, name: `welcome`})
    }
    await next();
});
```

Are you using DirectLineJs with Web Chat or your own custom client?

**Comment by EricDahlvang** [comment]
You can also add properties to the .from:

```js
from: { id: 'userid', name: 'username', xyz: "this is a test" },
```

These will then be present in the `activity.From.Properties`:
![image](https://user-images.githubusercontent.com/11055362/60054667-07b0e000-9690-11e9-9f95-24a77779dc88.png)

Support for the .Properties already exists in the .Net sdk, and has just recently been added to the javascript sdk: https://github.com/microsoft/botbuilder-js/pull/999  This will come out with the next sdk version, which should be in the next few weeks.

**Comment by Adityagrao** [comment]
> You can send a backchannel event from DirectLineJs to the bot with custom data in the activity's value property when the connection is established. See the code snippets below.
> 
> **DirectLine**
> 
> ```js
> import { DirectLine, ConnectionStatus } from 'botframework-directlinejs';
>  
> var directLine = new DirectLine({
>     secret: '<DIRECTLINE_SECRET',
> });
> 
> directLine.activity$
> .filter(({ from }) => from.role === 'bot')
> .subscribe(
>     activity => console.log("received activity ", activity)
> );
>  
> directLine.connectionStatus$
> .subscribe(connectionStatus => {
>     switch(connectionStatus) {
>         case ConnectionStatus.Online:
>           directLine.postActivity({
>               from: { id: 'myUserId', name: 'myUserName' },
>               type: 'event',
>               name: 'webchat/join',
>               value: { locale: 'en-US' }
>           }).subscribe(
>               id => console.log("Posted welcome event, assigned ID ", id),
>               error => console.log("Error posting activity", error)
>           );
>           break;
>     }
> });
> ```
> 
> **Bot - Node SDK**
> 
> ```js
> this.onEvent(async (context, next) => {
>     if (context.activity.name === 'webchat/join') {
>         await context.sendActivity({ text: `Welcome to Web Chat! Your locale is set to ${context.activity.value}`, name: `welcome`})
>     }
>     await next();
> });
> ```
> 
> Are you using DirectLineJs with Web Chat or your own custom client?

I am using DirectLineJs on my custom client with AngularJS, which is connected to the Bot written in C#

**Comment by cwhitten** [comment]
see https://github.com/microsoft/BotBuilder-Samples/issues/1589 for an update on how the ConversationUpdate event is fired in the Direct Line protocol

**Comment by xtianus79** [comment]
Great question and answer!
