### ISSUE TITLE
Paginate through history

### ISSUE THREAD

**Issue by kkhanstella** [microsoft/BotFramework-DirectLineJS#185]
Getting history with MS Bot, directline or REST API with watermark doesn't seem to be sufficient for getting history.

We have a long running conversation in a conversational interface, where we would like to display somewhat last x messages in the conversation, each time user see the oldest message, they would be able to request more conversation history, but with current watermark implementation if I want to retrieve history earlier than some offset then this is not possible because directline will return list of all messages from the watermark till the most recent one.

Is there a way to paginate through the history get maximum of X items since watermark position?

**Comment by EricDahlvang** [comment]
Hi @kkhanstella 

The cache of messages in the Direct Line connector service is intended to be used as a connection reliability mechanism, not as an actual message history store.

If you require more granular control over conversation history, you will need implement an a transcript store server side.  And, you can use the [SendConversationHistoryAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.conversationsextensions.sendconversationhistoryasync) api to send chunks of history messages to the conversation.

We do not currently have a complete example demonstrating this, but it is in the works.
