### ISSUE TITLE
Handling "retry" results in duplicate message from bot

### ISSUE THREAD

**Issue by yoshigev** [microsoft/BotFramework-DirectLineJS#188]
Hi,

We are using the JS SDK for connecting our Node.JS application to various bots.
We noticed something that looks like a bug in the bot framework, but I'm posting this message here as this is the channel in use.

In case a bot takes more than 15 seconds to process an activity, the bot framework responds with "502 Bad Gateway" with body that contains { code: "BotError", message: "Failed to send activity: bot timed out" }.
The SDK converts this response to { id: "retry" } result, which is sent to the client application.

Our client application detects the "retry" result and re-sends the activity.

The problem begins when the bot finishes processing the activity and sends an activity as a response.

From the bot point-of-view, it has received 2 separate activities (the second one will probably arrive after the bot has changed its state, so might be rejected as something that was not expected).

From the client point-of-view, it will eventually receive 2 separate activities - one is the result of the first activity, and the second is the result of the re-send.

It looks like a problem in the bot framework, as normally when a server replies with an error code it means the request was not handled at all, while in this case, the request handling was just prolonged (it is strange that the bot framework handles the reply from the bot after the timeout  was expired).

There is a discussion about handling retries in https://github.com/Microsoft/BotFramework-DirectLineJS/issues/76, but it doesn't seems like there is a solution to our problem there.

I must note that I understand that it is not good practice to have a bot that takes so much time to respond, but I'm looking for a way to deal with it from the client side.

Thanks,
Yehoshua

**Comment by orgads** [comment]
ping

**Comment by cwhitten** [comment]
Hi @yoshigev. Thanks for reporting this issue. I'm looping in the Support team to investigate and look for a reproduction to the issue. We will report back our findings and next steps soon. Thanks.

**Comment by tdurnford** [comment]
@yoshigev  I would recommend sending your response from a [Proactive Message](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript) if it is going to take longer than 15 seconds to respond. The issue is that the bot cannot respond with the appropriate status in the allotted time because it is getting hung up on processing the request. Instead, if you initialize a proactive message in the the `onMessage` handler, the bot will continue processing the activity and send the correct status response to Direct Line before it times out. Take a look at the code snippet below.  

```javascript
this.onMessage(async context => {
  const conversationReference = TurnContext.getConversationReference(context.activity);
  context.adapter.continueConversation(conversationReference, async turnContext => {
    await new Promise(resolve => setTimeout(resolve, 20000));
    await turnContext.sendActivity('Hello, World!');
  });
});
```
Hope this helps!

**Comment by yoshigev** [comment]
Thank you @tdurnford for your reply.

As I explained in the question, I'm not looking for a way to fix the bot code.
I'm looking for a way to handle "bot error conditions" in the client side.
With the current way the DirectLine API works, we've not found a way for the client to infer the status/state of the bot (whether it has handled the request or not).

Maybe I can explain it in another way:
When the client posts an activity to the bot framework, the bot framework assigns an ID to that activity.
This ID can later be used for example by "replyToId".
Our problem is that the client has no way to get the ID that **was created by the framework** if the bot had some failure when handling the activity.

**Comment by tdurnford** [comment]
Per the Direct Line documentation regarding [sending an activity](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0#response), the activity ID is included in the response from the bot if the request is successful. As I mentioned in my last comment, a successful response is only sent after the bot is done processing the incoming activity. With the current architecture, there is no way to receive the activity id if the bot failed to process the message.

>  When the activity is delivered to the bot, the service responds with an HTTP status code that reflects the bot's status code. If the bot generates an error, an HTTP 502 response ("Bad Gateway") is returned to the client in response to its Send Activity request.

> If the POST is successful, the response contains a JSON payload that specifies the ID of the Activity that was sent to the bot.
