### ISSUE TITLE
Direct Line Client Example?

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-DirectLineJS#19]
It would be super cool if this repo included a working example client demo. ;-)

**Comment by billba** [comment]
Can you suggest a sample?

**Comment by nwhitmont** [comment]
I am currently looking for an example to test with.

**Comment by billba** [comment]
I'm asking for specifics. "client demo" covers a lot of ground. What would it do? There's already sample code in the README - what more are you looking for?

**Comment by ergodaveh** [comment]
We're interested in suggesting a Speech Enable Webchat example

**Comment by billba** [comment]
@ergodaveh WebChat is now speech-to-text enabled...

I'm closing for now, but could reopen it if someone would suggest a sample.

**Comment by slidenerd** [comment]
A generic sample customer support bot would work wonders

**Comment by billba** [comment]
@slidenerd that is not a client example
