### ISSUE TITLE
Reconnect to a conversation

### ISSUE THREAD

**Issue by Zack-Strife** [microsoft/BotFramework-DirectLineJS#191]
Hello,

As the [doc](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0) says : "If you have "Enhanced authentication option" enabled in the Direct Line settings, you might get a 400 "MissingProperty" error saying no user ID specified." when trying to reconnect to an existing conversation. 

Is there a fix or a workaround ?  Disabling enhanced authentification force me to use a magic code when using oAuth Card, which I'd like to avoid.

**Comment by tdurnford** [comment]
Related to https://github.com/MicrosoftDocs/bot-docs/issues/412

**Comment by tdurnford** [comment]
When you try to reconnect to a conversation with Enhanced Authentication enabled, Direct Line checks the bearer token for the user id.  Evidently, you need to use a token that has the same user and conversation ids as the conversation you are trying to reconnect to, so basically, you need to use the same token that you used to initialize the conversation. I'm guessing you are trying to use your Direct Line secret,which does not have a user or conversation id, instead of a token.

**Comment by EricDahlvang** [comment]
The wording on that doc should be stronger.  Reconnecting to an existing conversation while enhanced authentication is enabled is not possible, by design.

**Comment by Zack-Strife** [comment]
Oh I see. Yes I'm indeed not passing the token as it already expired, and I'm using the secret. 

So, if by design we can't reconnect while enhanced authentication is on, I'm bound to have a magic code right ? It's always one or the other (or else I use the token but that's only until it expires)

**Comment by Jeffders** [comment]
When enhanced security is on, you cannot reconnect using a secret. You can only reconnect using a non-expired token that includes the user id. 

You can refresh the token at regular intervals to make sure you have an active one. The documentation for that API is here:

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0

So if you are reconnecting with a valid token, you can use Enhanced Security and get no-magic code, as well as be able to reconnect the WebSocket.

**Comment by Zack-Strife** [comment]
> When enhanced security is on, you cannot reconnect using a secret. You can only reconnect using a non-expired token that includes the user id.
> 
> You can refresh the token at regular intervals to make sure you have an active one. The documentation for that API is here:
> 
> https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0
> 
> So if you are reconnecting with a valid token, you can use Enhanced Security and get no-magic code, as well as be able to reconnect the WebSocket.

That implies that either the server should store and refresh the token everytime before it fails OR that the user client has to be always on and sending events to refresh the token. 
Both are highly undesirable and probably worse than getting a magic code.  All would be well if we could refresh the token with an expired one like in oauth
