### ISSUE TITLE
Testing pipeline for Streaming Extensions for DirectlineJs

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-DirectLineJS#192]
Our CI/CD should do regression testing for streaming.

**Comment by compulim** [comment]
This is completed. @ckkashyap now has a test harness that can be used to test DLJS and it run on CI. And also a hosted and continously deployed environment that everyone can try out.

**Comment by compulim** [comment]
Go to https://compulim.github.io/webchat-loader and select "MockBot with Streaming Extensions" for a quick test on the latest build of DLJS.
