### ISSUE TITLE
Streaming fault tolerance: handling happy/unhappy scenarios

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-DirectLineJS#193]
(Edited by @compulim to complete the list)

Here is the list, we should expand into multiple issues later. Asterisks are shipblockers.

- (18) Happy path
   - (12) With ⭐ and without conversation ID in sending messages (user to bot)
      - ⭐ Typing #196 #201
      - ⭐ Text messages (including attachments, but the test case is defined later below) #197 #202
      - ⭐ Event #198 #203
      - ⭐ JSON messages
         - `postBack` with text or JSON #199 #204 #206 #207
         - `messageBack` with `displayText` #200 #205
   - (6) With and without CID in receiving messages (bot to user)
      - ⭐ Typing #208 #211
      - ⭐ Text messages (including attachments) #209 #212
      - ⭐ Event #210 #213
- (1) End conversation #214
- (5) Interrupted
   - (2) Able to resume after interruption
      - ⭐ Due to network error (will retry) #215
      - ⭐ Resume after page refresh (conversation ID is kept) #216
   - (2) Not able to resume after interruption
      - ⭐ Due to expired token (will request renew token) #217
      - ⭐ Due to blocked/throttled (should stop everything) #217
   - ⭐ Resume by a renewed token #219
      - This make sure the renewed conversation can be continued by both side
      - If the Web Socket did not killed after token is expired, the test must kill it to make sure the new token is working properly
- (1) ⭐ Failed before first connect (a.k.a. airplane mode) #220
- (2) OAuth
   - ⭐ With magic code #221
   - ⭐ Without magic code #222
- (4) Upload
   - ⭐ A single file with and without a text message #223 #224
   - ⭐ Multiple files with and without a text message #225 #226
- (2) Conversation update
   - ⭐ Should be sent initially when using a token with user ID #227
   - ⭐ Should not be sent initially when not using a token with user ID #228
- (2) Renew token
   - ⭐ With a non-expiring token #229
      - This is overlapping with the test above, this test is focusing on whether the token can be renewed or not, regardless the renewed conversation can be continued or not
   - ~With a secret (keep same conversation ID)~ #230
      - (This is not working today)
- ~(1) Add a sideband stream (while chat activities are actively ongoing)~ #231
   - (This is not working today)
   - ~Start a new sideband stream~
   - ~Stop a sideband stream~

**Comment by compulim** [comment]
Will fill out more on this.

**Comment by compulim** [comment]
I am expanding this into individual issues so we can track them easily.

**Comment by compulim** [comment]
Unassigned CK as we split out all tasks. This issue serves as TOC for now.

**Comment by ckkashyap** [comment]
William has already created individual tasks.
