### ISSUE TITLE
Question | Directline message Ids

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/BotFramework-DirectLineJS#2]
Same question: https://github.com/Microsoft/BotBuilder/issues/2170, just hoping for a quick response. 

So we've got a web interface which uses https://www.npmjs.com/package/botframework-directlinejs (works really well) and we use the fact that messages returned via directline (bot and user msgs) have a messageId of the format "G0SRNz7iwTiLehjQsXk3tI|0000001", "G0SRNz7iwTiLehjQsXk3tI|0000002" etc to sort on the sent and received ones on our FE. 

However... Messages (Activities) in the bot code itself have a messageId of the format of a GUID. Even if you got to that point in code from a request via directline. 

So my question is: does directline have some sort of interception and enrichment of the messages (ids) on your side before returning to the user? Why then do these messages not have the same ID in our bot code itself?

Reason I'm asking is, we broadcast messages to a separate 'admin-console' via signalR. But the message has a GUID id. But the message had a directline id on the webchat side.

You can imagine how this mucks with sorting messages in their correct order. Especially as the timestamp on the messages is not reliable - messages are frequently in the wrong order. 

Any feedback very much appreciated.

**Comment by billba** [comment]
I'll let the BotBuilder folks respond. Definitely not a client issue.
