### ISSUE TITLE
ES6 support limitation on Azure function to use DirectlineJS

### ISSUE THREAD

**Issue by ronak-itility** [Microsoft/BotFramework-DirectLineJS#23]
Azure functions seems to support node 6.5.0 max [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version-and-package-management) and that version seems not well supported for es6 [node.green](http://node.green/)

Any solution for ?

### Purpose
Create an adapter using DirectlineJS which is Http Triggered and output binding with Azure Bot (Framework) to connect with the bot.

**Comment by billba** [comment]
DirectLineJS is written in Typescript then transpiled down to ES5.

**Comment by billba** [comment]
Closing due to lack of response.
