### ISSUE TITLE
Happy path: sidebanding a stream

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-DirectLineJS#231]
1. Start a conversation
1. Add a new stream, sidebanded with the activities (i.e. not activities, but custom payload)
1. Communicate with the bot using activities, both ways
1. Add payload to the stream

Make sure:
- The stream is a stream, not packet
- The stream has a long life (across multiple activities)
- The stream can be started/stopped while activities are ongoing
- The stream will not interfere with activities
- More than one streams can be started simultaneously

**Comment by Jeffders** [comment]
This sort of 'sandbanding' is not supported. The stream must be isolated for our use and must follow our protocol.

**Comment by cwhitten** [comment]
@Jeffders are backchannel events supported?

**Comment by Jeffders** [comment]
Yes, once you have the websocket opened, you can send whatever activity you want (like an EventActivity). Is that what you mean?

**Comment by cwhitten** [comment]
Yes, I imagined it would be as simple as that but wanted to confirm. @compulim can you expand a bit on this requirement and the scenarios it intends to cover?

**Comment by compulim** [comment]
I thought Streaming Extensions could be used to multiplex streams to the bot, e.g. sending WebRTC traffic.

But looks like it is only for piggybacking HTTP packets only, i.e. sticky session and removing middlemen.
