### ISSUE TITLE
startConversastion under IE11

### ISSUE THREAD

**Issue by jacyuan** [microsoft/BotFramework-DirectLineJS#233]
Hello everyone,

We meet some strange issues while trying to integrate our chatbot into a client's host page (under liferay I believe). Indeed, everything works fine under chrome and firefox, but not for IE11.

While using IE11, we got a 401 during the startConversation http call, and the reason is that :
normally, the startConversation func send an empty body for post call, but under ie11, we don't know why, the body is changed to "undefined" as a string (http header has also been updated with "Content-Type	text/plain;charset=UTF-8").

Yesterday, I tried to add "body:undefined" into the function, but it does not help.
(now, I tried again to use "body:{}", let's wait and see)

Appreciated if you got some experiences to share about this.

Thanks a lot

**Comment by compulim** [comment]
Hi @jacyuan.

Do you think your page loaded a polyfill that will interfere with `XMLHttpRequest`?

For example, if you open <kbd>F12</kbd> console and type `XMLHttpRequest`, do you see `[native code]` like the screenshot below?

![image](https://user-images.githubusercontent.com/1622400/65542681-733f5f00-dec4-11e9-8a4d-c6fc3dc989fc.png)

It sounds like something is interfering with `Observable.ajax()` function, which will in turn call `XMLHttpRequest`.

I checked the network traffic when using IE11 with DirectLineJS, it did not send `undefined` as the body.

![image](https://user-images.githubusercontent.com/1622400/65542968-11cbc000-dec5-11e9-91f3-ad43b387173e.png)

So I am guessing something loaded in your page that interfere with `XMLHttpRequest` and it is buggy about `body: undefined`.

**Comment by jacyuan** [comment]
Hi @compulim,

I think you're right.

Indeed, direct line works well alone under IE11, but since our client integrated the chatbot under  liferay, this might be the reason for this issue (maybe caused by liferay, or maybe caused by the codes of our client).

While debugging this morning under IE11, I do see things (more specifically errors) in a js file, loading xmlHttpRequest functions (prototype). I was thinking about some kind of "transcription", or calls to lower level libraries, which translate incorrectly an empty body. But since I'm not really familiar with this part, I didn't go further.

But yes, this makes sense.

Thanks
