### ISSUE TITLE
Detect an error when posting activity

### ISSUE THREAD

**Issue by gareththackeray** [microsoft/BotFramework-DirectLineJS#234]
Is it possible to detect that the `postActivity()` results in an error?  I tried intercepting the `postActivity()` method and subscribing to the activity before returning it, but for some reason this results in a double-send of the message.

Is there a recommended way of doing this?  I can't find anything in the documentation here or in the WebChat repo.

Thanks.

**Comment by jacyuan** [comment]
Hello @gareththackeray, seen from the code, when resulting in error, the postActivity func throws, in some case (expired token, some http errors), "retry" as result, as well as some other errors.

In our project, we've already tested to chain a .subscribe(...) after postActivity : 
- when everything's going well, I got the current conversatsion Id (? or maybe activity id, I forgot the detail),
- in case of errors, I'll get "retry" as string, or other things.

I don't know whether that's gonna help.

**Comment by tdurnford** [comment]
@jacyuan is correct. The `postActivity` method returns an Observable that you can subscribe to. When the activity is sent successfully, it will return the activity id, and when there is an error, it will prompt you to retry sending the message.

https://github.com/microsoft/BotFramework-DirectLineJS/blob/048651f8254caffe9b6661e5fa771adab793bd92/src/directLine.ts#L386

**Comment by gareththackeray** [comment]
@jacyuan do you think you could send me a code snippet of you chaining onto the subscribe?  The way I'm doing it causes a duplicate message to be sent to the bot.  Many thanks.

**Comment by jacyuan** [comment]
Hi @gareththackeray , I've done nothing more than
.postActivity(....)
.subscribe(x=>
//if the value of x is 'retry', do your retry logic here
//else, some other logic here
)

I don't think adding a subscribe will send twice the message, but maybe somewhere else (the way you do your retry, or maybe a global exception catcher ?).
