### ISSUE TITLE
Message reordering and delay

### ISSUE THREAD

**Issue by yoshigev** [microsoft/BotFramework-DirectLineJS#245]
Hi,

We are using botframework-directlinejs for connecting a voice (telephony) channel to Azure bots. The client is configured to use WebSocket.
We have encountered the following problem: In case the bot sends several activities as a response to a single user activity, the responses are sometimes received in the wrong order.

From reading some replies to other issues, we understand that order of the activities is not guaranteed, but we have not found a solution for re-ordering the activities, especially because there is some unexplained delay (of about 300 ms) between the received activities.

For example, this is the normal behavior with no reordering:
```
Client                         Direct Line         Bot
                      
hi ------------------>
                                          -------> hi
                                          <------- first response
                                          <------- second response
first response <------ (id: 2)
(300 ms delay)
second response <----- (id: 3) 
(300 ms delay)
hi (echo) <----------- (id: 1)
```

And, this is a problematic behavior, with reordering:
```
Client                         Direct Line         Bot
                      
hi ------------------>
                                          -------> hi
                                          <------- first response
                                          <------- second response
second response <----- (id: 3) 
(300 ms delay)
first response <------ (id: 2)
(300 ms delay)
hi (echo) <----------- (id: 1)
```

If it weren't for the delay, we could have buffered the three messages and reorder them. However, adding a delay of 600 ms is not acceptable in our case, as it will add to the existing delay from the speech-to-text and text-to-speech engines.
Also, if the echoed message ("hi"), would have been received first, we could have identified the reordering immediately (by noticing a gap in the IDs). However, as it is *always* last to be received, there is no way to identify "real"gaps.

So, my questions are:

1. Why is there a delay between the received activities over the WebSocket?
2. Why is the echoed message received last?
3. Is there a way to identify when reordering occur, without waiting for all the activities to be received?

Thank you,
Yehoshua

**Comment by compulim** [comment]
Thanks for reporting, love the way you express the issue, very professional. It has all the details we need.

Answering your question:

1. (See point 1 below)
1. tl;dr this is by design
   - The echo message is an ACK
   - ACK means, the bot finish reading/processing the message
   - Which means, the bot finished sending all outgoing messages, so the BOT can ACK the original message
   - You can look at proactive messaging, which can be considered a way to "ACK sooner". Proactive message is designed for starting a background processing task. So the bot will "ACK first" then send both activities later as a background processing task.
1. If you know there will be multiple outgoing activities (i.e. fragments), few options you can consider
   - Use `channelData` and send fragmentation info to your client. So your client know how to expect all activities to come before synthesizing over the phone
   - Group messages into a single activity with multiple attachments

Few things:

1. Could you look at the `timestamp` property on the activity? Is the first response has a earlier timestamp than the second one?
   - Activities are asynchronous. When the bot send both activities to our servers, they may actually reach different servers (the sending is a HTTP POST call)
   - If you would like to introduce delay between activities, you can also take a look at proactive messaging
2. Although the ID has a sequential number, don't relies on it

@carlosscastro could you follow up with this? I believe this is related to channel side than client side.

**Comment by DDEfromOR** [comment]
Pinging @mickeydjw to bring this up during LSI review.

**Comment by yoshigev** [comment]
Hi @compulim,

Thank you for the compliment and for the very detailed answer.

Some more information I gathered:
- When reordering occurs, the `timestamp` values are ordered correctly - according to the order the bot sent the activities (meaning that the first response has an earlier timestamp than the second one, although the second one is received first).
- The delta between the `timestamp`s is also ~300 ms, which probably means the delay is not introduced by the DirectLine channel. I currently suspect the HTTP POST of `await turnContext.SendActivityAsync` call by the bot, but I didn't get to measure it so far.
- When reordering occurs, I see that the delta between the `timestamp`s is around 50-100 ms (I was mistaken at the example in my original post). After digging some more in the logs, I see that there are also occasions of low delay that did not resulted in reordering.
- When using polling instead of WebSocket, the normal behavior is that the echo (the ACK) is received first. I'm not sure this is aligned with the explanation you gave above.

Also, I'm not sure I understand your explanation about proactive message (I must admit that I work on the DirectLine client side, and not on developing bots). From what I see on the code of one of our bots, when it sends several responses it uses `await turnContext.SendActivityAsync`. This call also appears on the example of proactive messages documentation. Does it mean we already use proactive messages?

Thank you for the suggestion to add a sequence number to channelData. This is probably what we'll do (although as a temporary workaround, we currently do rely at the sequence number of the ID).

**Comment by compulim** [comment]
Assigning to @DDEfromOR, @carlosscastro, and @mickeydjw. I believe this is channel-side issue.

**Comment by compulim** [comment]
@yoshigev Probably you are not using proactive messaging.

For proactive messaging, you should be calling `getConversationReference()`, then save that JSON somewhere.

When you code is ready, you rehydrate the BotFrameworkAdapter/TurnContext with that JSON and continue. The rehydration can took place outside of your current box.

I will leave @DDEfromOR and @mickeydjw to answer your Q1.

**Comment by DDEfromOR** [comment]
@yoshigev if you can provide me with a Bot ID and conversation ID (older than 45 minutes to make sure it's expired, but newer than 28 days to make sure it's still in our logs) I can check our logs to see if there's a specific operation causing the delays.

**Comment by yoshigev** [comment]
@DDEfromOR , I've make a fresh run that experience both the delays and the reordering.
The client sends a single message with the text `{\"Text\":\"Hi.\",\"NumReplies\":10}`.
As a reply, the bot sends 10 activities, which look like: `{\"Text\":\"Hi.\",\"Index\":0}`, with sequential "Index" values.
On the client side, the activities are retrieved in the following order and times (sadly, the clocks are not synchronized):
```
Client time    Activity timestamp   ID seq#    Applicative "Index"    Times delta (ms)
--------------------------------------------------------------------------------------
07:34:52.192   07:34:51.5255377     0000003            1                   666
07:34:52.195   07:34:51.7059364     0000004            2                   489
07:34:53.102   07:34:51.3599299     0000002            0                  1742
07:34:53.104   07:34:51.9848984     0000005            3                  1119
07:34:53.450   07:34:52.8911938     0000006            4                   559
07:34:53.684   07:34:53.1903167     0000007            5                   494
07:34:53.922   07:34:53.4738652     0000008            6                   448
07:34:54.270   07:34:53.7862902     0000009            7                   484
07:34:54.506   07:34:54.0725125     0000010            8                   433
07:34:54.853   07:34:54.3693985     0000011            9                   484
```
The "Time delta" column shows the delta between the client time and the activity timestamp.
Note the huge delay of the 3rd and 4th replies (although I cannot be sure that its not some hiccup of the client), which corresponds to the occurrence of reordering.

The delay between the responses (according to the activity timestamp) varies between 166ms and 312ms with one occurrence of 906ms (of the 5th reply).

The bot ID is "ron-echobottmptest" and the conversation ID is "G4oqSILT1Np6HcuDDWTFnI-h".

**Comment by DDEfromOR** [comment]
@yoshigev from looking at the logs I see your bot is located in the West Central United States while your client is connecting from West Europe, which probably accounts for the extra latency. This is probably due to WCUS being the default location of new resource groups created in Azure, which in turn causes the bot's App Service to run in the same region, as it's tied to the resource group's location. I suspect the routing of return messages may be in part to blame for the bot messages arriving out of order, too.

I'm not seeing any other apparent causes for the latency, so I'm afraid my best suggestion is to create a resource group in West Europe and [move the resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-move-resources) to it, or create a new resource group in West Europe and redeploy the bot to it. 

For what it's worth I can say the bot itself responds quickly and appears healthy, and the majority of the latency is being incurred on the client to bot path. I also see two instances where messages failed to reach the bot within 15 seconds within the last 24 hours, but both appear to have been automatically retried and succeeded on the second try.

**Comment by yoshigev** [comment]
Thank you @DDEfromOR for your analysis.
I performed a new check with a bot that is located in West Europe and indeed no special delays were seen.
I'm still not sure I understand why delays occur when working in a distant region. If the bot sends several consecutive activities towards the bot framework (which I'm not sure where it resides) and the bot framework forwards those activities to the client, what causes the delay *between* the responses (I would expect that there will be a constant delay, and afterwards all the responses will arrive together).

In any case, is there a way for the client to check what region it is connected to and what is the region of the bot, so it can raise some alarm if the regions don't match?
Or better, force the client to connect through the region of the bot? (I've tried setting the "domain" parameter to "https://bc-directline-wcus.azurewebsites.net/v3/directline" but it resulted in 400 error response when trying to open the WebSocket connection.)

**Comment by DDEfromOR** [comment]
@yoshigev the delays are a byproduct of the different series of hops the messages make while going between the bot and services, in general the larger the geographical distance the more hops the message will make and more latency will be introduced. If you ping against your bot's endpoint using any http tracing tool you can get a better idea of how many hops is involved in routing the traffic back and forth.

You can force the client to connect to the closest instance of the bot, but it involves a couple of extra steps. You would need to create multiple App Services and deploy your bot to each, standing one up in each region you want guaranteed low latency in, and then stand up an Azure Traffic Manager and follow [these tips](https://docs.microsoft.com/en-us/azure/traffic-manager/traffic-manager-configure-geographic-routing-method) for creating a geographic routing profile for it to use. Finally you would create a channel registration bot with the bot service and set it's endpoint to point to your traffic manager. This causes clients to connect to your traffic manager and be directed to the nearest app service instance running your bot.

**Comment by yoshigev** [comment]
Thank you @DDEfromOR, but I think you missed my question.

We are using WebSocket for receiving activities from the bot. WebSocket is based on TCP which assures ordering of messages regardless of the IP-level routing of the packets. This means that the re-ordering and the delay between messages occur *inside* the bot framework core network.

From what I understood from you, when I connect from West Europe, I use resources of the bot framework in West Europe even if the bot is deployed in WCUS, and this causes the reordering and delays *behind* the DirectLine front server.

My question is: Can I use bot framework / DirectLine resources of WCUS even if I connect from West Europe?

@compulim, Do you know why I get 400 error response to the WebSocket when I try to use "https://bc-directline-wcus.azurewebsites.net/v3/directline" domain? Do you know of another way to select the region?

**Comment by vishwacsena** [comment]
@DDEfromOR can you help take a look?

**Comment by yoshigev** [comment]
Just to clarify my question.
In current setup, my client connection to the bot looks like:
```
Client ....... DirectLine server .............................. Bot (service endpoint)
Europe            Europe                                        US
```
In such setup, delay and re-ordering occurs between the messages.

I think the following topology will solve the delays between the message, without incurring additional delays:
```
Client ............................. DirectLine server ........ Bot (service endpoint)
Europe                                    US                    US
```

So, my question double:
1. Is it possible to work in the proposed topology (e.g., by letting the client determine the region of the DirectLine resources)?
2. Is there is a way for the client to identify that the bot reside in a "far" region (so even if 1 is not possible, the administrator can be notified that the topology is not optimal)?

**Comment by DDEfromOR** [comment]
Hi @yoshigev ,

Thank you for clarifying! I was writing up a more detailed version of what you've accurately and succinctly described in diagrams above, but you clearly understand the topography correctly and I would have been missing the question again. 

As far as I know the answer to question 1 is yes, but would be in the domain of @compulim and WebChat. 

Question 2 would be a bit more complicated and would probably require adding the region to the bot as an environment variable and having the bot either include the value as channelData in replies or expose an endpoint specifically for getting this information before contacting the channel to create a conversation. As it is I'm not aware of any way of getting this information from out-of-the-box bots or via the channel.

**Comment by cwhitten** [comment]
@yoshigev, DirectlineJS's public api accepts a `domain` field, documented as followed:
```javascript
var directLine = new DirectLine({
    secret: /* put your Direct Line secret here */,
    token: /* or put your Direct Line token here (supply secret OR token, not both) */,
    **domain**: /* optional: if you are not using the default Direct Line endpoint, e.g. if you are using a region-specific endpoint, put its full URL here ***/
    webSocket: /* optional: false if you want to use polling GET to receive messages. Defaults to true (use WebSocket). */,
    pollingInterval: /* optional: set polling interval in milliseconds. Default to 1000 */,
});
```

Are you able to utilize this to pin to a specific region?

**Comment by yoshigev** [comment]
> Are you able to utilize this to pin to a specific region?

@cwhitten, I tried using the option, but I'm not sure what is the domain name for the region-specific endpoint.
As I wrote above, setting it to "https://bc-directline-wcus.azurewebsites.net/v3/directline" resulted in 400 error response when the client SDK tried opening the WebSocket.

**Comment by DDEfromOR** [comment]
@yoshigev I found a [blog post](https://blog.botframework.com/2017/02/02/Direct-Line-performance-improvements/) with the regional directline endpoints listed, but I can't find anything more specific than  Asia/Europe/NorthAmerica.

**Comment by yoshigev** [comment]
Thank you @DDEfromOR.
I get the same 400 error as I got for the ```bc-directline-wcus.azurewebsites.net``` domain.

Logs (I needed a hack to get the directline-js debug to work on Node.JS):
```
creating WebSocket wss://northamerica.directline.botframework.com/v3/directline/conversations/HKZ4Boaq6Js8riSeaX0n7r-6/stream?watermark=-&t=ew0KICAiYWxnIjogIlJTMjU2IiwNCiAgImtpZCI6ICJBT08tZXhGd2puR3lDTEJhOTgwVkxOME1tUTgiLA0KICAieDV0IjogIkFPTy1leEZ3am5HeUNMQmE5ODBWTE4wTW1ROCIsDQogICJ0eXAiOiAiSldUIg0KfQ.ew0KICAiYm90IjogInJvbi1lY2hvYm90dG1wdGVzdCIsDQogICJzaXRlIjogIl9aWjExR2FpYklNIiwNCiAgImNvbnYiOiAiSEtaNEJvYXE2SnM4cmlTZWFYMG43ci02IiwNCiAgIm5iZiI6IDE1Nzk2ODk3MjQsDQogICJleHAiOiAxNTc5Njg5Nzg0LA0KICAiaXNzIjogImh0dHBzOi8vZGlyZWN0bGluZS5ib3RmcmFtZXdvcmsuY29tLyIsDQogICJhdWQiOiAiaHR0cHM6Ly9kaXJlY3RsaW5lLmJvdGZyYW1ld29yay5jb20vIg0KfQ.tFyXgXnkrphOA4sKis70aocOIIk9oWBr8GAwYvarbG3DVq6MGKXWyndTq_UpbOo51HGnqHDJC-hE9vy-2GnG-WBRCwLnklhxo0tXnzFfRonVENthyig95xH4jJjldoBBpjZ49mQJe4cVgZNHBvJuTTGKxNzb_EPMcm-eWUEwDrJncbRzmLirI9Rgs0yaBmsXMgxQD5LxHiXxbPkExlzzPoncvPQmlqsPzhFavW1blveeor6kQMIr9cL99XNv5o6XqKxRjwmS4YhIsfn-Up24wFAwf7mC9iYvuH2ko-VssIfU_nsl3Tbi_BOv3g8KemSd0q0WGtopLvJm_sne-rfU8w
postActivity {
  type: 'event',
  name: 'channel',
  value: 'telephony',
  channelData: {
    callee: '333'
  },
  from: { id: '+972541234568' },
  locale: 'en-US'
}
Error: Unexpected server response: 400
    at ClientRequest.<anonymous> (E:\Project\node_modules\ws\lib\websocket.js:579:7)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (E:\Project\node_modules\ws\lib\websocket.js:697:15)
    at ClientRequest.<anonymous> (E:\Project\node_modules\ws\lib\websocket.js:579:7)
    [... lines matching original stack trace ...]
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
```

BTW, besides the problem itself, this causes an uncaught exception which causes the whole process to terminate. ```ws.onerror``` should be added.

**Comment by yoshigev** [comment]
I now see that my colleague has already reported the uncaught exception on #170.

In any case, the regional directline endpoints don't work with WebSocket.

**Comment by DDEfromOR** [comment]
Hi @yoshigev , sorry the wait! I repro'ed this and I think we've uncovered a gap in our documentation.

Can you try setting your domain to https://northamerica.directline.botframework.com/v3/directline/ with webSocket set to true? For me I'm able to establish a websocket WebChat session by using the region domains with the versioning endpoint affixed to the end.

For reference I'm using the vanilla example from the WebChat repo readme with the above changes:
```
      <script>
         window.WebChat.renderWebChat(
            {
               directLine: window.WebChat.createDirectLine({
                  token: '<DirectLine Token>',
				  domain: 'https://northamerica.directline.botframework.com/v3/directline/',
				  webSocket: true
               }),
               userID: 'YOUR_USER_ID',
               username: 'Web Chat User',
               locale: 'en-US',
               botAvatarInitials: 'WC',
               userAvatarInitials: 'WW'
            },
            document.getElementById('webchat')
         );
      </script>
```

**Comment by clearab** [comment]
@yoshigev - please let us know if you have any further questions on this issue.

**Comment by yoshigev** [comment]
Apparently I had some network issues on my side (a firewall) that prevented me from using the regional endpoints. I will need to conduct more tests later to see if the regional endpoints indeed reduces the delays and reordering.

In any case, I think that the behavior is now clear, and no real problem was discovered, so the issue can be closed.

Thank you all. Your feedback was very valuable.
