### ISSUE TITLE
Post image base64 to bot-framework occurs "ajax error 400"

### ISSUE THREAD

**Issue by shunyh** [microsoft/BotFramework-DirectLineJS#250]
Hi team,

I got an error when post image base64 as an attachment:
![image](https://user-images.githubusercontent.com/7311188/69937494-eba24c00-1515-11ea-98f5-164eef0c4386.png)

Post method:
![image](https://user-images.githubusercontent.com/7311188/69937992-1640d480-1517-11ea-8cf3-3f9ddab5c288.png)

Timestamp(UTC):
12/2/2019, 6:50:52.579 AM - 12/2/2019, 7:00:00.579 AM

Conversation Id:
BjLrX2HlHsE6jpjasNFSNb-l

The image base64 string is too large to paste here, will cause this page crash.

The size of this image/png is :
![image](https://user-images.githubusercontent.com/7311188/69937782-974b9c00-1516-11ea-9422-0b0200193948.png)

Does it caused by the base64 string too long and not allowed to post?

Can you tell me the limited size of the image?

Looking forward to your insight.

**Comment by handsomeyao77** [comment]
Additionally, it can be uploaded successfully if I save the base64 string as an image then post to bot-framework.

![image](https://user-images.githubusercontent.com/7311188/69939261-5eadc180-151a-11ea-80a3-c4fdaa3acbe3.png)

**Comment by mdrichardson** [comment]
I don't believe 281 KB would be an issue.

Can you expand the `request` portion of that error message to see if your attachment was included appropriately?

Does your `contentUrl` (base64 image string) formatted like `data:image/png,<theBase64String>`? Note that the `data:image/png,` part is required.

If you have that, can you send me a link to the image so I can try to repro?

**Comment by handsomeyao77** [comment]
@mdrichardson 
I saved the image  base64 string as a text file and post to [GitHub](https://github.com/handsomeyao77/sharefiles/blob/master/base64String.txt). Please try to access it.

I am sure the contentUrl starts with "data:image/png," I have a conditional sentence for this

![image](https://user-images.githubusercontent.com/7311188/70015167-89018c80-15b7-11ea-9562-29f4403ea971.png)

**Comment by handsomeyao77** [comment]
Request partion:
![image](https://user-images.githubusercontent.com/7311188/70016835-5dcd6c00-15bc-11ea-8345-59d0cb1b28e6.png)

![image](https://user-images.githubusercontent.com/7311188/70016861-69b92e00-15bc-11ea-8378-a577621771dd.png)

**Comment by mdrichardson** [comment]
@shunyh I was able to successfully post using your base64 string, so that doesn't seem to be the issue.

Can you set a breakpoint or `console.log()` `contentUrl` to ensure it looks as it should? Maybe it's duplicating the `data:image...` part?

Are you able to send messages that *don't* have that image?

If you can share your code (taking out any sensitive information), I might be able to help more.

**Comment by shunyh** [comment]
@mdrichardson I can post text message and some images that base64 string is smaller than the above one.
![image](https://user-images.githubusercontent.com/7311188/70106294-35a64180-167e-11ea-95f8-5560898610e2.png)

And I print the `contentUrl` by `console.log()`, the format is correct.

![image](https://user-images.githubusercontent.com/7311188/70106101-b9abf980-167d-11ea-8898-71de71ca7aea.png)

![image](https://user-images.githubusercontent.com/7311188/70106071-aac54700-167d-11ea-8300-64a3bc3b07b1.png)

BTW, our services are in Mooncake, but bot-framework service is hosting on Global Azure, does it affect the attachment message pipeline?

    `postActivityWithAttachment(from, contentUrl) {
       console.log(contentUrl);
       this.hidePasteImageModal();
       this.props.startLoading();
       let thumbnails = [];
       thumbnails[0] = contentUrl;
      this.botConnection
      .postMessageWithAttachments({
        type: "message",
        text: "Send a screenshot.",
        from: {
          id: from.id,
          name: from.name
        },
        attachments: [
          {
            contentType: "image/png",
            contentUrl: contentUrl,
            name: 'screenshot.png'
          }
        ],
        channelData: {
          thumbnails: thumbnails
        }
      }).subscribe(
        id => {
          this.props.stopLoading();
          Logger.trackEvent('PasteEvent', {
            message: 'Paste image from clipboard and send succeed.'
          });
        },
        error => {
          this.props.stopLoading();
          Logger.trackEvent('PasteEventError', {
            message: 'Paste image from clipboard but send failed.',
            fromId: from.id
          });
          console.log(error);
        }
      );
    }`

Background:
Directly paste images from the clipboard.

    `// retrieve image and convert to base64
    function retrieveImageFromClipboardAsBase64(pasteEvent, callback, imageFormat) {
          if (pasteEvent.clipboardData == false) {
          if (typeof (callback) == "function") {
          callback(undefined);
           }
        };

     var items = pasteEvent.clipboardData.items;

     if (items == undefined) {
         if (typeof (callback) == "function") {
          callback(undefined);
        }
     };

    for (var i = 0; i < items.length; i++) {
    // Skip content if not image
    if (items[i].type.indexOf("image") == -1) continue;
    // Retrieve image on clipboard as blob
    var blob = items[i].getAsFile();

    // Create an abstract canvas and get context
    var mycanvas = document.createElement("canvas");
    var ctx = mycanvas.getContext('2d');

    // Create an image
    var img = new Image();
    var maxSize = 480;
    // Once the image loads, render the img on the canvas
    img.onload = function () {
      // Update dimensions of the canvas with the dimensions of the image
      // mycanvas.height = img.height > img.width ? maxSize : ~~(img.height / img.width * maxSize);
      // mycanvas.width = img.width > img.height ? maxSize : ~~(img.width / img.height * maxSize);
      mycanvas.width = this.width;
      mycanvas.height = this.height;

      // Draw the image
      ctx.drawImage(img, 0, 0, mycanvas.width, mycanvas.height);

      // Execute callback with the base64 URI of the image
      if (typeof (callback) == "function") {
        callback(mycanvas.toDataURL(
          (imageFormat || "image/png")
        ));
      }
    };

    // Crossbrowser support for URL
    var URLObj = window.URL || window.webkitURL;

    // Creates a DOMString containing a URL representing the object given in the parameter
    // namely the original Blob
    img.src = URLObj.createObjectURL(blob);
    }
    }`

**Comment by mdrichardson** [comment]
@shunyh I'm not familiar with Mooncake and can't seem to find out anything about them through a quick search, so I'm not sure. If you can try hosting your services elsewhere and are still able to reproduce the issue, that might narrow it down.

Your code and base64 all look fine and I'm not able to reproduce this, so I'm guessing the issue is with Mooncake somehow.

**Comment by shunyh** [comment]
@mdrichardson thanks for your patiently reply, you help me a lot.

We have to deploy services on Mooncake due to our users can't access the service on Global Azure, they will be blocked by the firewall.

I will limit the size or downscale the image before posting to the bot-framework to avoid this error.

And I am looking forward to your team release the 'Directly paste images from clipboard' feature.

Thank you again.

**Comment by mdrichardson** [comment]
@shunyh You're welcome. Just note that I'm not 100% sure that the issue is a Mooncake problem, maybe 80%. If you decide to test with another service and still run into the issue, feel free to re-open this.
