### ISSUE TITLE
Bot framework v3 - Sending events from bot using DirectLine

### ISSUE THREAD

**Issue by RitekR** [microsoft/BotFramework-DirectLineJS#253]
Hi,

We are using DirectLine to create an event and to greet the  User. We have used following piece of code in our project to send the activity as an event :

 function LoadBotChatUI() {

        dlContext =  @Html.Raw(ViewBag.dlContext);
       var dl = window.WebChat.createDirectLine({ secret: dlContext.dlToken });
        window.WebChat.renderWebChat({
           directLine: window.WebChat.createDirectLine({ token: dlContext.dlToken }),
        username: dlContext.user.name,
        userID: dlContext.user.id,
        bot: { id: '@System.Configuration.ConfigurationManager.AppSettings["BotId"]' },
        resize: 'detect'
      }, document.getElementById("bot"));

        dl.postActivity({
                from: dlContext.user,
                name: 'requestWelcomeDialog',
                type: 'event',
                value:  '@ViewBag.JWTtoken'
            })
            .subscribe(function (id) {
                console.log('"trigger requestWelcomeDialog" sent');
            });

    }
To handle this activity  we have used below condition:
 else if (message.Type == ActivityTypes.Event)
            {
Adaptive card to greet user
}
   This code was working fine till  12/05/2019, But now we are getting activity type as conversation update instead of activity type as an event once we open chat window.
CDN Used :   https://cdn.botframework.com/botframework-webchat/master/webchat-es5.js

Anybody can gimme an example about how can we fix this in v3 using c#?

**Comment by stevkan** [comment]
Look over sample [15.d.backchannel-send-welcome-event](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event) from the BotFramework-WebChat repo. It details the preferred method for sending an event back to the bot. Setup is the same for either C# or other.

**Comment by stevkan** [comment]
Closing as resolved.
