### ISSUE TITLE
IE11 won't send files

### ISSUE THREAD

**Issue by rcambrj** [microsoft/BotFramework-DirectLineJS#257]
When trying to upload a file with IE11, the activity will "succeed" with an id of `retry`, and will never actually succeed. I narrowed this down to here: https://github.com/microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L784 where the XHR to convert the `data:` URL into an `ArrayBuffer` fails. The error message presented is:

    ```Access is denied```

There is only [one other issue](https://github.com/microsoft/BotFramework-DirectLineJS/issues/233) I could find that's related, which suggests that `XMLHttpRequest` is being polyfilled, but logging that suggests that it isn't in my case (I get `[native code]`).

I couldn't find much else on the web about IE11 failing to satisfy a `data:` XHR request, other than [this stackoverflow question](https://stackoverflow.com/questions/30896571/running-an-xmlhttprequest-on-a-data-url-on-internet-explorer-10) which suggests it's not possible.

So my recommended fix is to stop using an XHR for this conversion and instead [perform the conversion with this short function](https://stackoverflow.com/questions/12168909/blob-from-dataurl), like so:

```
cleansedAttachments.forEach(function (media) {
    var blob = dataURItoBlob(media.contentUrl);
    formData.append('file', blob, media.name);
})
```

For proof, I thought I'd isolate this issue in a sandbox: https://jsbin.com/moyebusena/edit?js,output (try this in IE11, the "Hello World!" message will not display)

Thoughts?

**Comment by vishwacsena** [comment]
@rcambrj thanks for reporting the issue and the PR. We will review the PR shortly.

**Comment by cwhitten** [comment]
@rcambrj thank you for your patience as the team ramps back up after the holidays.

**Comment by Virtual-Josh** [comment]
@cwhitten Can you follow up on this one? Thanks.

**Comment by compulim** [comment]
I will follow up this one.

**Comment by compulim** [comment]
Better, the `postActivity` function should accept `activity.attachments.content` as an `ArrayBuffer` and we can read it directly without parsing.

Today, we are reading attachment from a `blob:` URL, which is created by calling `URL.createObjectURL()`. Is it a viable workaround in your solution?

**Comment by cwhitten** [comment]
Our preference is to guide users to the above workaround provided by @compulim . Closing this for now but please re-open if the workaround does not satisfy your needs.
