### ISSUE TITLE
Streaming: error handling in directline streaming

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-DirectLineJS#263]
Line 233 does not have any error handling. add error handling when the url is not existing or when the do() fails.

**Comment by carlosscastro** [comment]
@compulim and @ckkashyap  agreed to do this in R8 timeframe.

**Comment by compulim** [comment]
https://github.com/microsoft/BotFramework-DirectLineJS/pull/183/files#r371435453

**Comment by compulim** [comment]
So the better idea is to do retry and error handling in a single block:

```js
let numRetries = 3;

while (numRetries-- > 0) {
  await connect();

  const fatal = await disconnectHandler();

  if (fatal) {
    throw new Error('fatal error');
  }

  await sleep(1000);
}
```

Or even better,

```js
let numRetries = 3;

while (numRetries-- > 0) {
  try {
    connectAndDoWork();
  } catch (err) {
    if (err.fatal) {
      throw err;
    } 
  }

  await sleep(1000);
}
```

Also, need to consider about aborting the connection, e.g. dev want to kill the client and stop the connection. The ES5 standard of handling these kind of cancellation token is called [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

**Comment by ckkashyap** [comment]
Changes have been pushed to ckk/protocoljs to address and reviewed by @compulim
