### ISSUE TITLE
Using on backend under proxy

### ISSUE THREAD

**Issue by oboloka** [microsoft/BotFramework-DirectLineJS#264]
Is there any way to use a proxy for all request in this library?

**Comment by stevkan** [comment]
Hi @oboloka, look over the [domain](https://github.com/microsoft/BotFramework-DirectLineJS/blob/master/README.md#create-a-directline-object) property that is assignable when creating a DirectLine object. I spoke with a colleague who suggested it is possible to factor in a proxy by use of "domain" but he also said it would likely be a fairly sizable lift to make happen.

In essense, the "domain" property acts as a kind of redirect which may allow you the ability to build in a proxy.

**Comment by oboloka** [comment]
Hi, @stevkan
Thanks for your answer!

To be honest, I don't want to implement another proxy server. I would rather prefer to use custom clients with `http.Agent` implementation that connects to a specified proxy server (e.g. https-proxy-agent).
I do see the possibility to pass properties for clients (`WebSocket` and `ajax`, but it's not documented):
`const bot = new DirectLine({
      secret: mySecret,
      WebSocket: myWebSocketWithProxy,
      ajax: myClientObservableWithProxy,
    });`

But it doesn't work out of the box. I had to override some methods in DirectLine to make it work.

Maybe it makes sense to have support for this case?

**Comment by stevkan** [comment]
Hi @oboloka,

Using the `domain` property does not necessitate your needing to implement another proxy server. The `domain` property simply allows you to specify an alternate destination for your web chat traffic to flow to. In this way, you can continue to use the proxy server you already have setup.

I'm been advised by one of our Direct Line devs that this is, in fact, the best approach for you to go forward. In short, you would use the `domain` property to point your Web Chat traffic to your proxy server. At the proxy server level, you will send out the API call to retrieve the Direct Line response (i.e. the `token`, `conversationId`, `streamUrl`, etc.). The `streamUrl` is the important item here as you will need to overwrite the `wss://directline.botframework.com/v3/...` endpoint with the websocket endpoint you have configured. This can then point to the actual Direct Line websocket endpoint to complete the circle.

Hope of help!
