### ISSUE TITLE
How to close a websocket connection using the lib from a Node.js app?

### ISSUE THREAD

**Issue by pintux** [microsoft/BotFramework-DirectLineJS#268]
Hi,

I'm using the lib in a Node.js app.
Is it possible to programmatically, explicitly, close a connection (close the related websocket) to a bot from the app?
Many thanks.

**Comment by stevkan** [comment]
No, unfortunately, this is not an option. The web socket is part of the server running the bot. In order to close the web socket, the server would have to be restarted with the web socket disabled.

**Comment by pintux** [comment]
Hi @stevkan, thank you for your reply. My question was about closing the websocket client-side, not on the bot server. In order to clean my app sockets connections.
