### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by spaniard81** [microsoft/BotFramework-DirectLineJS#273]
Is there any sample code/application that illustrates the use of the DirectLine JS API? As such the code snippets in the README.md or on Azure Docs page are not very informative to get a head start, at least for someone who is a beginners.

**Comment by CezaryMarcjan** [comment]
Thanks @spaniard81 for the report..

**Comment by cwhitten** [comment]
The API documentation and example code is here: https://github.com/microsoft/BotFramework-DirectLineJS#how-to-create-and-use-a-directline-object

We do not have working samples available for users for this library.

**Comment by spaniard81** [comment]
"We do not have **working** samples available for users for this library." @cwhitten So how do someone know this library works? Do you know of any project on GitHub that is using this? Would be have some reference. Working samples offer people a head start in their tasks (reducing the efforts from a few days to few hrs).

**Comment by cwhitten** [comment]
hello @spaniard81. BotFramework WebChat uses this library and is open source. Browse the samples in that project to different uses: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples

**Comment by spaniard81** [comment]
Thank you @cwhitten, I was also thinking about looking at the WebChat.
