### ISSUE TITLE
Delays in receiving and response of messages

### ISSUE THREAD

**Issue by srikarcheruku** [microsoft/BotFramework-DirectLineJS#279]
Hi 

We are using directline-js for connecting to azure bots from zendesk chat-widget, everything works fine for most of the time i.e, we get the response the message 2-4 seconds, but sometimes the bot takes more than 30-40 seconds to respond for a simple question. We checked in app-insights the time took by the bot-service is not more than 5 seconds. We are not sure why these delays are happening.Here are the conversation id's for such examples, can you let us know are there any abnormalities for these conversations from directline perspective

**Conversation ID 1**: DtjQmkX8IMQDLb8CHkkqyE-p%7C0000008
This conversation took 32139ms which started at 10:32:38 AM but the request was received by the bot service at 10:33:11 AM

**Conversation ID 2**: CXj8YGLA355Jr0XXFvX7cj-p%7C0000000
The chat has been started at 10:23:32 AM but was received by the bot at 10:23:50 AM, the bot service processed the request within a minute and responded back, but the message was received at 10:23:56 AM(6 seconds gap) to the client .

**Conversation ID 3**: 5gyaJxZMp8NIlmq1jKGSf8-p%7C0000016
This is the third scenario in which there was no response received by the client even though the bot service has responded to the request at 10:41:38 AM

And here is the microsoft APP ID: **34d88a4e-046b-43ac-affd-49f86f759815**

Please do point out if any other details required to process this request.

**Comment by mdrichardson** [comment]
All of the backend Directline logs look great/normal. As you can see here, all requests complete very quickly once they hit Bot Framework services:

![image](https://user-images.githubusercontent.com/40401643/81206770-6ec24500-8f81-11ea-8967-001f1a4f80ef.png)

![image](https://user-images.githubusercontent.com/40401643/81206785-72ee6280-8f81-11ea-9c1e-a9d6324a3b9d.png)

![image](https://user-images.githubusercontent.com/40401643/81206795-7681e980-8f81-11ea-98b3-4521ce2e9196.png)

I'm also not seeing anything systemic on our side.

Looking into your app, specifically, I see:

![image](https://user-images.githubusercontent.com/40401643/81206891-9addc600-8f81-11ea-8315-330e05a52ed2.png)

I believe that `services.visualstudio.com` is used for App Insights. Are your users experiencing any issues, or are you only seeing the time discrepancies in App Insights?

**Comment by srikarcheruku** [comment]
thanks for the reply @mdrichardson, 
Actually our users are experiencing some delays in the chat window and we are not seeing any such delays in our app insights where the response is taking more than 30 seconds.

Attaching chat script of a user where they experienced a delay for the 1st case:
![image](https://user-images.githubusercontent.com/55845976/81209148-09de0d80-8fc8-11ea-8984-e459f2077660.png)


I can see that there is a lot of time taken for the message to be received by the direct line from the user and also in the second case the user received the message at 9:23:56 which is 6 seconds after the directline processing the response activity.

What could be the possible reason for this?

**Comment by mdrichardson** [comment]
It's tough to say. Considering all of the Bot Framework logs look fine, I'd imagine that the delay is somewhere between the client and DirectLine. Generally, even if something within the bot itself takes more than 15 seconds, it will produce 502 GatewayTimeout errors. But again, we can see in our logs that roundtrip time from when Directline receives the message, the bot processes it, and Directline sends it back is mere seconds.

How are you generating those chat scripts? Is it something on the client side or bot side? What non-Bot Framework services does your bot use? How about your client?

**Comment by srikarcheruku** [comment]
The chat scripts are from the client side(zendesk chat-widget), and we are using redis cache which is  non-bot framework services in bot, while the client is zendesk chat widget in which we integrated directline-js using websockets.

And one more point is the client service is hosted in AWS while the bot solution is hosted in azure.

**Comment by mdrichardson** [comment]
@srikarcheruku Can you add additional logging into your client to track timestamps of every outgoing HTTP Request? As there's nothing in App Insights or DirectLine that indicates any kind of slow-down on our end, I'm inclined to close this issue as it seems to be something on the client. I'm willing to keep it open, though, if you feel otherwise.

**Comment by srikarcheruku** [comment]
Yes @mdrichardson we will log additional logs at client side, we can close this issue for now i will let you know in case if we need any more assistance from you.
Thanks for your help.
