### ISSUE TITLE
Add support for posting ConversationUpdate types

### ISSUE THREAD

**Issue by DL-LiveTiles** [Microsoft/BotFramework-DirectLineJS#28]
Hello,
Trying to post a event of type ConversationUpdate, but the type is not currently supported.
Can either the validation on the type be removed or the IConversationUpdate interface be implemented.
Thank you,
Douw

**Comment by billba** [comment]
That is a synthetic activity that is posted by the Connector. It is not meant to be sent by WebChat.

**Comment by DL-LiveTiles** [comment]
@billba We want to manually trigger this event earlier as WebChat only raise it on the first message, which is not ideal for our flow.
How can we trigger this event manually?

**Comment by billba** [comment]
You can't, but you can send an Event activity through the backchannel.
