### ISSUE TITLE
Conversation connection ended suddenly

### ISSUE THREAD

**Issue by shunyh** [microsoft/BotFramework-DirectLineJS#283]
Hi team, this issue occurs again since [Conversation end](https://github.com/microsoft/BotFramework-DirectLineJS/issues/275)

ConversationId : KrpeUD3Ii74640PV07MTGA-l
Timestamp(UTC): 2020.05.26 08:10:38 --2020.05.26 08:25:38

![image](https://user-images.githubusercontent.com/7311188/82988326-8befae00-a02b-11ea-86d3-130fdeea294d.png)

Looking forward to your insights!

**Comment by gabog** [comment]
Closing this one as we are tracking this as part of #275.
