### ISSUE TITLE
Refused to get unsafe header "x-ms-bot-id"

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-DirectLineJS#287]
## Screenshots

![img](https://user-images.githubusercontent.com/22778273/84424498-0cd6aa00-abd5-11ea-9213-2b0dd09f606a.png)

## Version

BotFramework WebChat CDN 4.9.1

## Describe the bug

I see an error under the console with message "Refused to get unsafe header 'x-ms-bot-id'".

**Comment by arman-g** [comment]
It could be that this header does not exist but it is being read which causes this error. A simple case [here](https://trackjs.com/blog/refused-unsafe-header/).

**Comment by NeriBarakat** [comment]
In my case I had element <header> under the body tags, when I placed the web chat container just under the body tag <body>, it worked fine for me.

**Comment by vishwacsena** [comment]
@ckkashyap @compulim can you help take a look and comment?

**Comment by compulim** [comment]
@swagatmishra2007 can you look at this one? This seems rooted from your PR, https://github.com/microsoft/BotFramework-DirectLineJS/commit/41f5df397a413d8878b9d570dffad2d50a3bc87e#diff-4ea468cc7b0c950f26da99e8ca71ac57R621.

**Comment by venkatx5** [comment]
Any solution for this error?

**Comment by srinaath** [comment]
@swagatmishra2007 Could you take a look at this ticket?

**Comment by fedsp** [comment]
Freshstart using react and bot framework directline (it is working well using a legacy webchat), same error. Does anyone has an update?

**Comment by swagatmishra2007** [comment]
It's an unused header..I will file a PR to remove it .

**Comment by lorenz-haenggi-axa** [comment]
we had the same issue - and we set back to version 4.9.0 and its fine. it only appears in 4.9.1 due to the fact that botframework-directlinejs was updated to 0.12.0 instead of 0.11.6

**Comment by grimz11** [comment]
Same issue here with <b>botframework-webchat": "^4.9.0"</> version. But this only happens in the live server though. There's no issue in my local.

**Comment by wbrands2** [comment]
SAME ISSUES*** Same issue here with botframework-webchat": "^4.9.0" version. But this only happens in the live server though. There's no issue in my local.

**Comment by SafwaanA-Hexaware** [comment]
Is there any solution to this issue?

**Comment by arman-g** [comment]
Is there any updates for this issue? What is the time line?

**Comment by SafwaanA-Hexaware** [comment]
I used the 4.8.0 version and this issue went away.

**Comment by compulim** [comment]
DLJS 0.12.0 is causing the issue, which was introduced in WebChat 4.9.1 (but not 4.9.0).

@swagatmishra2007 to get to this sooner.

**Comment by EricDahlvang** [comment]
Fixed with https://github.com/microsoft/BotFramework-DirectLineJS/pull/296
