### ISSUE TITLE
Node.JS support

### ISSUE THREAD

**Issue by poul-kg** [Microsoft/BotFramework-DirectLineJS#29]
I've tried to run sample code from Readme in Angular2 and it works perfectly.

However it doesn't work in NodeJS.

I've added code to track connection status, here is what I got in console.

```
the status when the DirectLine object is first created/constructed
currently trying to connect to the conversation
```

no other errors or messages in NodeJS console. I do not see any message about successful connection.

NodeJS `v7.4.0`

**Comment by poul-kg** [comment]
The problem I have is that I'm trying to write a mobile chat app. I'm using FuseTools for that, but FuseTools do not support some features which are supported by browsers, so I wanted to create a small Node.JS proxy. My app will communicate via available supported socket transport with Node.JS and Node.JS will communicate via DirectLine with ChatBot.

**Comment by danmarshall** [comment]
DirectLineJs is using RxJs/AjaxObservable which is meant for use in a DOM environment. You may be able to swap it with a "universal" - see https://github.com/ReactiveX/rxjs/issues/2099

**Comment by danmarshall** [comment]
Also, please see #20 , this might be a duplicate.

**Comment by poul-kg** [comment]
Ok, looks like adding `global.XMLHttpRequest = require("xhr2");` to the top of the main `.js` file, can solve this issue. I wasn't sending any messages, that's why connection status was not updating
Thanks @danmarshall
