### ISSUE TITLE
Support locale at StartConversation

### ISSUE THREAD

**Issue by timenick** [microsoft/BotFramework-DirectLineJS#292]
##Issue
Original issue: microsoft/botframework-obi#75

This issue tracks a frequently requested feature to allow a user locale when starting new conversations. The user locale is needed so that bots can send a properly localized Greeting Message to users.

##Proposed change
DirectLineJS - update the protocol to support locale and userId

Tracking WebChat issue: https://github.com/microsoft/BotFramework-WebChat/issues/3296

**Comment by compulim** [comment]
@youyu16 I saw you were assigned to this issue. So please let me know if the assignment is wrong so we can re-assign to someone else.

The goal should be:

```diff
  new DirectLine({
+   locale: 'en-US',
    token
  })
```
