### ISSUE TITLE
How to embed bot in html page.

### ISSUE THREAD

**Issue by SUGPZ** [Microsoft/BotFramework-DirectLineJS#31]
How can I embed a direct line channel bot in html page? How can I call my bot in html page div section ?

**Comment by tobybrad** [comment]
The very simplest way would be just to use the existing Webchat control which is, effectively, exactly that.

Are there scenarios you had in mind for which the webchat would not be suitable?

**Comment by SUGPZ** [comment]
Is Webchat UI editable? I want to edit the Chat UI according my website UI.

**Comment by tobybrad** [comment]
@billba will be able to authoritatively help you out there but the webchat is OSS, MIT licensed and available here: https://github.com/Microsoft/BotFramework-WebChat

There's a good section there on using CSS to style the chat here: https://github.com/Microsoft/BotFramework-WebChat#customizing-webchat. If you need to go deeper that is also well covered in the section starting here: https://github.com/Microsoft/BotFramework-WebChat#easy-in-your-non-react-website-run-webchat-inline

Hope that's of some use to you.

**Comment by SUGPZ** [comment]
Thank you so much. This is what I want. Thanks.
