### ISSUE TITLE
MediaType does not support word, pdf, xmls or other document types.

### ISSUE THREAD

**Issue by reyesrico** [microsoft/BotFramework-DirectLineJS#32]
MediaType is only rendering images, videos and audio files.

**Comment by billba** [comment]
Can you flesh this out? What would you like DirectLineJS to do differently?

**Comment by compulim** [comment]
## Note to fixer

Looks like there is a bug on this line of code, https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L562.

`Message.attachments` is of type `Attachment` and not `Media`. Don't know why TypeScript is not catching it.

We have `UnknownMedia` and it should be enough to help @reyesrico case.

**Comment by cwhitten** [comment]
Loading this up for prioritization in our upcoming milestone.
