### ISSUE TITLE
Typescript Issue with export

### ISSUE THREAD

**Issue by drfbwilliams** [microsoft/BotFramework-DirectLineJS#321]
Hi,

I created a plain vanilla asp.net core 3.1 mvc solution. pushed through with npm installs etc, all good. Index page has a single button on - as plain and basic as the site can be to run.

I create a TS file and added the following:
`import { DirectLine } from "botframework-directlinejs";
    var directLine = new DirectLine({
        secret: "<<secret>>",
    });
`

Regardless of how I set up the tsconfig.json, I am consistently blocked with this error:
Uncaught ReferenceError: exports is not defined

Reviewing the JS - it is failing on transpilled:
`Object.defineProperty(exports, "__esModule", { value: true });`

Any pointers here would be seriously appreciated.

**Comment by stevkan** [comment]
@drfbwilliams, I am going to start attempting a repro of this. In the mean time, can you post the code of your `tsconfig.json` file and the contents of your `package.json`?

**Comment by drfbwilliams** [comment]
Hi Steven - thanks for this.

I've tried down versioning TS back into the 2.1.x and still no apples.

So back to 4.0.3 - compiles

tsconfig.json
`{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "wwwroot/js"
  },
  "include": [
    "scripts/**/*"
  ]
}`


package.json
`{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "devDependencies": {
    "botframework-directlinejs": "^0.13.1"
  }
}
`

Simple test connect TS - bot-test.ts:


`import { DirectLine } from "botframework-directlinejs";

var directLine = new DirectLine({
    secret: "[secret]",
});

directLine.activity$
    .filter(activity => activity.type === 'message' && activity.from.id === 'mybot')
    .subscribe(
        message => console.log(message)
    );

function connectDirectLine() {
    directLine.postActivity({
        from: { id: 'myUserId', name: 'myUserName' }, // required (from.name is optional)
        type: 'message',
        text: 'a test post activity message'
    }).subscribe(
        id => console.log("Posted activity, assigned ID ", id),
        error => console.log("Error posting activity", error)
    );

    directLine.activity$
        .filter(activity => activity.type === 'message' && activity.from.id === 'yourBotHandle')
        .subscribe(
            message => console.log("received message ", message)
        );
}
`

Many thanks

**Comment by drfbwilliams** [comment]
Hi @stevkan ,

The only way to get around this is to use webpack, which is another train smash of dodgy "magic string" technologies.

I'm now hitting the other issue reported of non resolvable stream module - pretty frustrating as I am sure you can imagine after a few days of trying to get, what should be a simple library include to run in a bare bones solution.

I will mark this as closed, and hope someone else doesn't waste days as well.

Thanks

**Comment by stevkan** [comment]
@drfbwilliams, I'm glad you were able to move past this. I also fought with it trying any number of suggested solutions and implementations, but none to success.

**Comment by drfbwilliams** [comment]
@stevkan glad it wasnt just me then ;-)  Cheers
