### ISSUE TITLE
Unable to upload files which are having size greater than 4MB

### ISSUE THREAD

**Issue by dstvishnu** [microsoft/BotFramework-DirectLineJS#325]
When we are trying to upload the file we are unable to upload the file which have the size greater than 4MB.

**Comment by stevkan** [comment]
@dstvishnu,

Unfortunately, the file size limit is set at 4MB on the Direct Line channel. The limit is the default limitation, as specified in the [MaxRequestLength](https://docs.microsoft.com/en-us/dotnet/api/system.web.configuration.httpruntimesection.maxrequestlength?redirectedfrom=MSDN&view=netframework-4.7.2#System_Web_Configuration_HttpRuntimeSection_MaxRequestLength) property of the http runtime, which Direct Line utilizes.

As you can see in these other discussions, this topic has already been addressed and is unlikely to change, at this time.

- https://github.com/microsoft/BotFramework-WebChat/issues/789
- https://github.com/microsoft/BotFramework-Composer/issues/3940
- https://github.com/microsoft/botframework-sdk/issues/5302

**Comment by stevkan** [comment]
Closing this as resolved.
