### ISSUE TITLE
Error: Unable to resolve module core-js/features/promise

### ISSUE THREAD

**Issue by jaykeerti** [microsoft/BotFramework-DirectLineJS#329]
Guys i am unable to use the module as this error pops up whenever I run

I have downgraded to 0.11.6 because of this issue:https://github.com/microsoft/BotFramework-DirectLineJS/issues/317
![image](https://user-images.githubusercontent.com/16056169/102705321-6585ae80-42ac-11eb-81db-0e8e28314686.png)

**Comment by joshgummersall** [comment]
Can you share some details about your usage? Is this for a Node .js project, a browser project, or something else?

Resolution with Node.js works properly as `core-js` is listed in the package `dependencies`. A quick test in the browser indicates that `dist/directline.js` has the correct dependencies bundled as well.

To use the bundled version of Directline you can try:
```html
<script type="text/javascript" src="https://unpkg.com/botframework-directlinejs@latest/dist/directline.js"></script>
```

**Comment by jaykeerti** [comment]
i was just working on react native project ([link](https://blog.expo.io/so-you-want-to-build-a-chat-app-with-react-native-expo-and-microsofts-bot-framework-4d2327f76ce3))
@joshgummersall This helped Thanks.
