### ISSUE TITLE
Directline Reconnect Issue

### ISSUE THREAD

**Issue by pvkas** [microsoft/BotFramework-DirectLineJS#338]
## Problem
- Directline sending all past activity when connecting to an old conversation

## Issue Description
Reconnecting to old conversation relies on [Reconnect Conversation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0#generate-a-new-websocket-stream-url) API. Microsoft API is currently having an issue where they are always returning `watermark=-` in API
![image](https://user-images.githubusercontent.com/38325083/111607877-aaaf7300-87fe-11eb-86a0-48ef3bfabec6.png)

We found the issue in directline when we tried to resolve this issue with Directline APIs.

I could not find place to register issue to directline api.
So, if it relates to any internal repository for direcltine kindly forward this issue to right place.

**Comment by piyushkacha75** [comment]
Please fix it as soon as possible, Suddenly why sending all activities on reconnect?
```
import { DirectLine } from 'botframework-directlinejs';

const dl = new DirectLine({
    secret: /* SECRET */,
    conversationId: /* the conversationid you stored from previous conversation */
});
```
@pvkas is specifying API call behind is `new DirectLine with conversationId`. 
Why suddenly sending all activities ????? 😠

**Comment by iAmrMohamed** [comment]
We had the same issue today, we removed the dash after the `watermark=` as a quick fix

**Comment by jarofbilly** [comment]
Same issue here, the streamUrl returned from reconnecting to a conversation forces `watermark=-` which means that all past messages get pushed down the websocket

**Comment by craigjensen** [comment]
This is a regression in the directline service.  The fix will go out with this week's release

**Comment by craigjensen** [comment]
Fix has been released worldwide.  Please reopen if you continue to see this issue
