### ISSUE TITLE
Update cross-fetch dependency to remove vulnerabilities.

### ISSUE THREAD

**Issue by christopherjbaker** [microsoft/BotFramework-DirectLineJS#349]
The version of cross-fetch currently in use (v3.0.4) which exposes a [DoS vulnerability](https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311). v3.1.0 and later (current is v3.1.2) have a node-fetch dependency that resolves this issue.

**Comment by compulim** [comment]
Thanks, we will bump it soon.

We just finished our last release and now in the work of bumping dependencies.

> Note to internal: this is related to Direct Line App Service Extension protocol and not used in Direct Line protocol.

**Comment by NicholasWilliamFreeman** [comment]
you all are the best and you know wht to do. wish i could be more help pls do whatever you need to im still homeless and dealing with stupid ppl taking my stuff and blah blah


________________________________

**Comment by compulim** [comment]
Still working on it but it's almost there, look at #351.

At least for now, `npm audit` say 0 vulnerabilities. 😉
