### ISSUE TITLE
Conversation Start Properties not being passed to the PVA Bot

### ISSUE THREAD

**Issue by kaust-technovert** [microsoft/BotFramework-DirectLineJS#352]
I am passing a variable while creating the DirectLine object that I am using for my Power Virtual Agent
![image](https://user-images.githubusercontent.com/86673833/131412204-625d8afc-aefd-4a6f-a5e6-b133b8ba9acf.png)

Like this.

However, when I am trying to access this variable in the bot topic, I am unable to.
![image](https://user-images.githubusercontent.com/86673833/131412834-46557bf1-30d9-408e-aba3-86f9c3917187.png)

As you see in the screenshot, I am supposed to get a "Yes" answer automatically but it is not detecting any value and the flow is moving the question topic.

I am a beginner with programming but I checked the source code on how conversationStartProperties is being used but I see that there are no references to that variable anywhere..?

![image](https://user-images.githubusercontent.com/86673833/131412676-01d865ce-bf2b-441a-865f-5c175e296f1f.png)

Kindly help me with this issue as I was unsuccessful in finding any relevant solution anywhere on the internet.
Thank you in advance.

**Comment by stevengum** [comment]
@kaust-technovert are you using Web Chat or are you directly using Direct Line JS in your client?

The ConversationStartProperties have a specific shape for the Start Conversation API, so it might be that what you're trying to achieve is not possible via this approach.

If you are using Web Chat, I recommend checking this sample: [04.api/a.welcome-event](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/04.api/a.welcome-event) for sending an Event activity to the bot with relevant data _before_ other activities begin to appear in Web Chat.

**Comment by kaust-technovert** [comment]
I am using DirectLineJS directly in my client, and there is also some custom implementation which I cannot mess with. So I cannot use WebChat.
Is there any example for passing ConversationStartProperties to the bot and be able to use it?

**Comment by srinaath** [comment]
@stevengum Are you aware of any way to pass ConversationStartProperties?

**Comment by compulim** [comment]
@zhipeng should know more about this topic.

**Comment by timenick** [comment]
@kaust-technovert like Steven said "The ConversationStartProperties have a specific shape for the Start Conversation API, so it might be that what you're trying to achieve is not possible via this approach."  We do not support passing customized parameters and value for now.

**Comment by munozemilio** [comment]
Closing as not supported
