### ISSUE TITLE
Whether to support the wechat mini program

### ISSUE THREAD

**Issue by yaqinbai** [microsoft/BotFramework-DirectLineJS#379]
Whether to support the wechat mini program

**Comment by tracyboehrer** [comment]
There is a WeChat channel in Azure Bot Service.  It would be possible to use a custom adapter.  As reference, there is the DotNot sample demonstrating this:  https://github.com/microsoft/BotFramework-WeChat/

That repo has not been updated in some time, so it is unknown if it is current enough.
