### ISSUE TITLE
 Get token without exposing secret publicly in Javascript

### ISSUE THREAD

**Issue by irezek** [Microsoft/BotFramework-DirectLineJS#38]
I'm creating custom chat window on a wordpress site (hosted outside Azure) for my bot using Direct line connector and Javascript, and to start conversation I need to specify Direct line SECRET or a TOKEN for my bot app. 
To get a token i have to make a REST call to https://directline.botframework.com/v3/directline/tokens/generate and add to header "Authorization : Bearer SECRET". 
I don't want to expose that SECRET publicly in my javascript file and I don't want to pass it as a URL parameter. 
What are my other options?
How to get token without exposing my bot Direct line SECRET to client?

**Comment by billba** [comment]
You would have to do this is in a web site you control.

________________________________

**Comment by hkusulja** [comment]
@billba so Microsoft Example is to put secret inside JavaScript file. But you are telling that it should be used only by server backend which will obtain token and pass it to the JavaScript? What is best practice for public web site with Microsoft Bot ?

**Comment by billba** [comment]
There are many scenarios where publishing the secret is no problem. All it really means is that anyone can put your bot on their web site. If what you want is for people to use your bot, that might be okay.

If you don't wish to publish your secret, then best practice is to have your website get it, and inject the token directly into the javascript of the web page it publishes. In [this code](https://github.com/billba/botchattest/blob/master/index.ts#L30), `botchattest` gets a token in the act of creating the web page containing WebChat.

Closing this issue.

**Comment by seca23** [comment]
@Hrcinjo 

You can generate a token in WordPress with PHP like this:

```
<?php

/* This code is used to generate a token, that is only valid for a single conversation,
 * this prevents other developers from including your bot in their website. By 
 * restricting their access to your bot secret. 
 */

$botSecret = 'Your bot secret';

$response = wp_remote_get( 'https://webchat.botframework.com/api/tokens', array( 'headers' => 'Authorization: BotConnector ' . $botSecret ) );
if( is_array($response) ) {
  $header = $response['headers']; // array of http header lines
  $token = $response['body']; // use the content
}

?>

```
If you want to do this in a non WordPress site, you can do it like this:

```
$botSecret = 'Your bot secret';

$options = array('http' => array(
    'method' => 'GET',
    'header' => 'Authorization: BotConnector ' . $botSecret
));

$context = stream_context_create($options);

$token = file_get_contents('https://webchat.botframework.com/api/tokens', false, $context);
```

?>

**Comment by billba** [comment]
@seca23 that is extremely helpful, thank you!

**Comment by seca23** [comment]
I know this is an old thread, but here is a C# version for obtaining a token:

```
protected string file_get_contents(string url)
{
    var contents = "";
    if (url.ToLower().IndexOf("https:", StringComparison.Ordinal) > -1)
    {
        var wc = new System.Net.WebClient();
        var directlineSecret = ConfigurationManager.AppSettings["DirectlineSecret"].ToString();
        wc.Headers = new WebHeaderCollection {{"Authorization", string.Format("BotConnector {0}", directlineSecret) }};
        var response = wc.DownloadData(url);
        contents = System.Text.Encoding.ASCII.GetString(response);
    }
    else
    {
        var sr = new System.IO.StreamReader(url);
        contents = sr.ReadToEnd();
        sr.Close();
    }
    return contents;
}
```
