### ISSUE TITLE
React Native throws exception on ws.send(null)

### ISSUE THREAD

**Issue by grootendorste** [Microsoft/BotFramework-DirectLineJS#39]
Please feel free to close this if you don't think it's an issue.

Using React Native in 20 seconds after the direct line was initialized, the app throws an exception in Android and iOS: "Unsupported data type" which comes from the WebSocket's send function. This happens because in the directline's code it explicitly sends through null to the send function. This works on React in Chrome and Safari. But on the app this always throws an exception.

My temporary solution was to comment out the directline's code where it throws an exception. Also using polling works but I don't want to. Do anyone else have this issue?

**Comment by grootendorste** [comment]
Here is the precise line of code: sub = Observable.interval(timeout).subscribe(_ => ws.send(null));

Is there a reason why it's sending null?

**Comment by tschnoelzer** [comment]
Hi Team,

same here... just a simple test:

 ```
componentDidMount() {

    let directLine = new DirectLine({
      token: "_sdWTnasdasdasd...."
    });

    console.log("mounted");

    directLine.postActivity({
      from: { id: 'myUserId', name: 'Timo' }, // required (from.name is optional)
      type: 'message',
      text: '123'
    }).subscribe(
      id => console.log("Posted activity, assigned ID ", id),
      error => console.log("Error posting activity", error)
      );

    directLine.activity$
      .filter(activity => activity.type === 'message')
      .subscribe(
      message => console.log("received message ", message)
      );

  }
```

error is Unsupported data type in WebSocket.send 124:10

**Comment by grootendorste** [comment]
I'm surprised no other people are having this issue.

**Comment by tschnoelzer** [comment]
Perhaps its because of npm / node version ?!? I am using node 8.2.1 and npm 5.3.0 ....

**Comment by grootendorste** [comment]
I'm using v8.3.0. It also gave a problem with 6.9.1. I'm having an issue changing node versions now, I actually had to uninstall it completely because something broke. But according the comments of that Observable.interval(timeout).subscribe(_ => ws.send(null));, it's there because of some chrome issue. So I'm having this issue on iOS and Android, not in web.

**Comment by billba** [comment]
I don't see any reason it couldn't send `{}` instead of `null`, would that fix the problem with React Native?

@dandriscoll periodically DirectLineJS sends empty messages up the WebSocket as a way of helping Chrome notice if the connection is broken so that we can reconnect. Right now we send `null` but are contemplating changing this to `{}` because React Native's WebSocket implementation doesn't allow us to send `null`. I assume you don't check the incoming messages on your end, but I want to be careful not to break anything.

**Comment by billba** [comment]
Another alternative is to make this behavior optional. But I think it might be generally useful for any WebSocket implementation that, like Chrome's, is a little lax about noticing WebSocket disconnections.

**Comment by dandriscoll** [comment]
Can you send an empty string? That's what the service is expecting.

**Comment by billba** [comment]
Sure. Out of curiosity, does the service do anything with non-empty strings?

**Comment by dandriscoll** [comment]
Right now nothing, but `""` and `null` are protected from future changes in a way that other values aren't.

**Comment by billba** [comment]
Got it. Okay, let's wait to hear from the React Native people and then I'll make the change.

**Comment by billba** [comment]
@grootendorste @tschnoelzer we are waiting for your feedback on his one.

**Comment by grootendorste** [comment]
Hi I'll try tonight, sorry I wasn't at my laptop for a while.

**Comment by billba** [comment]
@grootendorste @tschnoelzer any news for us, React Native folks?

**Comment by grootendorste** [comment]
Hi all, sorry I've been on my other github account. A while ago I forked the repo and removed the .send(null) part and since then I haven't had any issues on any browser (on React) or any device (on React-Native). I apologize, I have not sent in an empty string (.send('')) yet to see if it works. But up until now removing the send completely has worked for me. I realize it's a cheap fix, but at the time I was in a rush.

**Comment by billba** [comment]
@grootendorste Thank you for the response. Unfortunately this doesn't help us evaluate the solution on the table.

**Comment by grootendorste** [comment]
@billba Sending {} instead of null also does fix the solution. I'm not a fan of quick fixes that I can't really motivate, can anyone explain why this is a good idea?

**Comment by billba** [comment]
@grootendorste we're looking to see if `send("")` fixes the solution.

This is not a quick fix.

We periodically ping the server to see if the connection is still good. We can't send just any message, but 
our server specifically ignores `null` and `""` as messages, so those are safe as pings. We had been sending `null`, which works in the browser, but breaks React Native. So since none of us here use React Native, we are trying to find out of `send("")` works on React Native.

**Comment by colewinans** [comment]
@billba `send("")` does indeed work. Confirming on React Native 0.50.

**Comment by billba** [comment]
Hooray, thank you @colewinans!
