### ISSUE TITLE
DirectlineStreaming - Retrying connection after end

### ISSUE THREAD

**Issue by orgads** [microsoft/BotFramework-DirectLineJS#391]
We're using the beta version of botframework-streaming for DirectlineStreaming on Node.

After a successful call which we end by calling `directLine.end()`, we're getting a warning on the console "Retrying connection Disconnected" every 7.5m more or less, and it never stops.

**Comment by orgads** [comment]
cc @compulim

**Comment by ramfattah** [comment]
Related to icm 361075809

**Comment by axelsrz** [comment]
@compulim could you provide an update on this, please?

**Comment by xieofxie** [comment]
pr is in progress: https://github.com/microsoft/BotFramework-DirectLineJS/pull/393

**Comment by orgads** [comment]
Fixed, closing this.
