### ISSUE TITLE
Angular 15 with botframework-directlinejs does not compile due to typings errors. 

### ISSUE THREAD

**Issue by ajeeshai** [microsoft/BotFramework-DirectLineJS#417]
While creating an Angular App with version 15 and adding the botframework-directlinejs, it does not compile. And shows this typings error

<img width="971" alt="image" src="https://github.com/microsoft/BotFramework-DirectLineJS/assets/154953874/b0e15908-4f0c-4520-a680-4103bbee62e4">

Steps to reproduce

- npx @angular/cli@15 new sample-app
- cd sample-app
- npm install botframework-directlinejs
- Change the app.component.ts to 

```
import { Component, OnInit } from '@angular/core';
import { DirectLine } from 'botframework-directlinejs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    const directLine = new DirectLine({});
  }
  title = 'sample-app';
}

```
- And run ./node_modules/.bin/ng serve

Or clone [this repo](https://github.com/ajeeshai/sample-angular-15-app-directline-js) , run npm install and run ./node_modules/.bin/ng serve

The latest angular version does not have this error. I wonder if it could be something related to the TypeScript version.

**Comment by ajeeshai** [comment]
Was able to fix it by using https://www.npmjs.com/package/network-information-types package.

**Comment by igor-h** [comment]
Hi @ajeeshai 

I'm facing same error with Angular 16.

```
Error: node_modules/botframework-directlinejs/lib/directLineStreaming.d.ts:13:26 - error TS2304: Cannot find name 'NetworkInformation'.

13     networkInformation?: NetworkInformation;
```

Then I installed the network information types, but nothing..
`network-information-types`

same error as well
