### ISSUE TITLE
Question: ChannelAccount object limitations

### ISSUE THREAD

**Issue by nicksav** [Microsoft/BotFramework-DirectLineJS#45]
Guys, I can't find any info on the allowed string length for From object
Can you please point me to the right direction?

**Comment by billba** [comment]
@dandriscoll?

**Comment by dandriscoll** [comment]
User IDs must be <= 64 characters in length. User names may be up to 256 characters.

**Comment by nicksav** [comment]
Ok thank you. What about properties object which part of Channel Account? Can put any json in?

**Comment by dandriscoll** [comment]
Extended properties on the 'from' field are not preserved. You can put whatever data you want in the ChannelData field.

**Comment by nicksav** [comment]
Thank you so much!
