### ISSUE TITLE
Constantly getting Failed to send activity: bot timed out

### ISSUE THREAD

**Issue by nicksav** [Microsoft/BotFramework-DirectLineJS#47]
Guys, I am in troubles. I am constantly getting 
{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot timed out"
  },
  "httpStatusCode": 504
}

and I am not sure why. Checking AI from web app, shows that the call is actually made and taking around 2 sec. to process. The back end also reply some message back and web chat client shows it. However, all activities I am sending, in Chrome showing with 504 error.

Bot Framework shows this error in DirectLine Chanel:
There was an error sending this message to your bot: HTTP status code GatewayTimeout

Any idea guys? Should I somehow reply something special to those activities?

Thanks
Nick

**Comment by danmarshall** [comment]
It may be that Direct Line is unable to connect to your bot. Is your bot behind a firewall? Any other network topology to be aware of?

**Comment by billba** [comment]
Closing due to lack of response.

**Comment by anandvardhandas** [comment]
It is happening to me as well but it is happening intermittently.

**Comment by DebanjanChakrabortyCN** [comment]
True here as well. I found that when I try to connect to webApp, after a delay ( say 45 mins ), and send a message, it returns me the same error. If however, I wait for another 1-2 mins, the socket itself returns the reply message that the backend has codeded

**Comment by vikramdadwal** [comment]
This issue still happening with latest BOT Framework 4.0. intermittently.
