### ISSUE TITLE
Allow users to reference conversationId property

### ISSUE THREAD

**Issue by harshithkashyap** [microsoft/BotFramework-DirectLineJS#48]
`conversationId` property is currently set to private [here](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L290). Users cannot reconnect to an existing conversation or handle `ConnectionStatus.ExpiredToken` state.

Change the access modifier to public to allow users to store `conversationId` externally in a db/localstorage.

This can be overcome by starting the conversation ourselves on the backend and passing streamUrl, token and conversationId to Directline constructor, but as of [this code](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L341), the `refreshToken` loop will not be run by directline and users have to manually handle it.

**Comment by billba** [comment]
That sounds right. Care to file a PR?

**Comment by harshithkashyap** [comment]
Gladly :)

**Comment by compulim** [comment]
We are tracking the resume story at #124, which will fix this issue.

**Comment by cwhitten** [comment]
See #124 for updates on this workstream
