### ISSUE TITLE
RefreshToken loop should be run even if user user provides streamUrl

### ISSUE THREAD

**Issue by harshithkashyap** [microsoft/BotFramework-DirectLineJS#50]
According to the following snippet [here](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L341-L353), the `refreshTokenLoop` function is only run if the `streamUrl` doesn't exist. 

```javascript
if (this.token && this.streamUrl) {
    this.connectionStatus$.next(ConnectionStatus.Online);
     return Observable.of(connectionStatus);
} else {
     return this.startConversation().do(conversation => {
         this.conversationId = conversation.conversationId;
         this.token = this.secret || conversation.token;
         this.streamUrl = conversation.streamUrl;
         this.referenceGrammarId = conversation.referenceGrammarId;
          if (!this.secret)
               this.refreshTokenLoop();
          this.connectionStatus$.next(ConnectionStatus.Online);
}
```

This is valid when starting a new conversation but when the user is connecting to an existing conversation, a `streamUrl` is returned while [requesting a directline token](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation).

As of now, we'll need to request a directline token for a conversation on the backend, ignore the `streamUrl` and only send `token` and `conversationId` to directline constructor. This would internally call same URL as that of backend to obtain the streamUrl leading to redundant calls.

```
GET https://directline.botframework.com/v3/directline/conversations/abc123?watermark=0000a-42
```

**Comment by compulim** [comment]
I think what you observe here is correct.

We need to revisit all resume/end/error/expired conversation stories, please track it at #124.

**Comment by cwhitten** [comment]
see #124 for updates on this workstream
