### ISSUE TITLE
Run on sentence in readme

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/BotFramework-DirectLineJS#56]
https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/README.md#reconnect-to-a-conversation

> The resultant Conversation object can then be passed by the app to DirectLine, which will

...will what? (maybe the words "which will" just shouldn't be there?

**Comment by danmarshall** [comment]
![image](https://user-images.githubusercontent.com/11507384/33627341-0e6496d6-d9b2-11e7-9649-da20af71a5ed.png)

**Comment by danmarshall** [comment]
I'll guess that "it will" should be removed, and should be a period.
