### ISSUE TITLE
Timeout 500: ECONNECTION timeout with some load with new state API implemented

### ISSUE THREAD

**Issue by droidpl** [Microsoft/BotFramework-DirectLineJS#59]
# Intro
Since the moment we started using the bot framework we have had random issues where the messages and the conversation requests returns 500 errors. We are about to go to production with the current bot and we did a load test to see how good or bad the bot can behave in different loads.

# Setup

Here I will comment the findings to see if they can help to understand where the bottleneck is. Basically our setup is:

- We have an azure server with the bot built with botbuilder in nodejs
- The storage we are using is tablestorage. It works properly as I checked the messages with Storage Explorer

# Code and calls
To build our clients, we have created in our server requests to send info to directline. Those requests to the bot are:
- /bot/messages -> The bot runs under this url
- /bot/message -> Sends a certain message to the bot. Attached the code.
```
BotHttpRequest.use(BOT_URL)
            .url(`/conversations/${message.conversationId}/activities`)
            .method('POST')
            .headers({
                Authorization: `Bearer ${directLineToken}`
            })
            .body({
                text: message.message,
                type: message.messageType,
                from: {
                    id: currentUser.registrationId,
                    name: currentUser.name
                }
            })
            .retries(3)
            .send()
            .then(function (response) {
                return response.data
            })
```

- /bot/convesation -> Starts a new conversation with the bot. The code is as follows:
```
BotHttpRequest.use(BOT_URL)
            .url('/conversations')
            .method('POST')
            .headers({
                Authorization: `Bearer ${directLineAuth}`
            })
            .send()
            .then(function (response) {
                return response.data
            })
            .then((data) => {
              // Send empty message so the conversationUpdate is triggered on the bot and adds the current user.
              // Otherwise, the current user will not be in the conversation and the greetings will not be triggered.
              const message = new BotMessageRequest({
                message: "",
                conversationId: data.conversationId,
                messageType: "message"
              })
              return this.sendMessage(message, currentUser, `BotConnector ${data.token}`).then(() => {
                return data
              })
            })
```

All this code works for small amount of requests but as long as it grows a bit (not too much), it just gets broken. 

# Issues

With this setup we did a test with a middle size machine from azure and this are the findings (test done with jmeter, 300 users, 5 requests per user):
- 64.81% of requests OK vs 35.19 KO
- 100% of the errors where error 500
- The response time per message is around 16s
- Most of the errors are ECONNECTION Timeout 15000ms (we also tried to increase the timeout with the same result)
- The total amount of requests done where 4262

Some errors we have seen in the server:
**Error 1**
```
ActivityId: 47bb6c41-0000-0000-0000-000000000000, Request URI: /apps/63e70998-1c00-470e-8093-b4ef0dac16b1/services/be412ef7-0aa4-462c-90cc-2ae92aeb435e/partitions/7b23a94a-4102-4a9e-9333-ee80a73e77fe/replicas/131556435222707878p/, RequestStats: , SDK: Microsoft.Azure.Documents.Common/1.19.162.2
    at Function.MongoError.create (D:\home\site\wwwroot\future-street\node_modules\mongodb-core\lib\error.js:31:11)
    at D:\home\site\wwwroot\future-street\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (D:\home\site\wwwroot\future-street\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (D:\home\site\wwwroot\future-street\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\future-street\node_modules\mongodb-core\lib\connection\connection.js:331:22)
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\future-street\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\future-street\node_modules\zone.js\dist\zone-node.js:151:47)
    at TLSSocket.ZoneTask.invoke (D:\home\site\wwwroot\future-street\node_modules\zone.js\dist\zone-node.js:345:33)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
```

**Error 2**
```
Error: connect ETIMEDOUT 40.127.139.252:443
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\home\site\wwwroot\future-street\node_modules\zone.js\dist\zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\home\site\wwwroot\future-street\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
```

(We also did a test disabling the bot insights correlation with no change on this)

In the report attached you will also see create anonymous and login, those are calls for our and those doesn't have any impact on the test.

Please let us know a way to reduce those numbers since those are not acceptable for a production ready bot.

Thanks for the support and best regards.
[Bot performance test result](https://github.com/Microsoft/BotFramework-DirectLineJS/files/1642851/Bot.zip)

**Comment by billba** [comment]
I'm sorry to hear about these problems, but this repo is for a JavaScript client library for the Direct Line protocol. May I suggest you post this issue at https://github.com/Microsoft/BotBuilder/?

**Comment by droidpl** [comment]
Ok, I will open this one on the other library. Thanks for the support.
