### ISSUE TITLE
Directline - There was an error sending this message to your bot: HTTP status code GatewayTimeout

### ISSUE THREAD

**Issue by premchandpl** [Microsoft/BotFramework-DirectLineJS#60]
All my bots are reposing with this message - There was an error sending this message to your bot: HTTP status code GatewayTimeout

Is there any issue in the direct line currently. None of my bots are responding

**Comment by EricDahlvang** [comment]
Gateway Timeouts occur when a bot takes longer than 15 seconds to respond.

**Comment by compulim** [comment]
Close due to inactivity.
