### ISSUE TITLE
WebChat using direct line unable to refresh token or reconnect

### ISSUE THREAD

**Issue by baki32** [Microsoft/BotFramework-DirectLineJS#62]
Hi,
on our project we're using webchat that is connecting to our bot through direct line without web sockets so we are able to restore chat history. After 15-30 minutes of inactivity when user tries to send message it immediately shows couldn't sent. I've tried to use reconnect API however looking into source code it seems that it's working only with web sockets enabled. I've tried to implement following options but neither of them is working and token always expires resulting on 403 error on token refresh.

```javascript 
var botConnection = new BotChat.DirectLine({ 
     secret: model.directLineSecret, 
     webSocket: false, 
     conversationId: getPersistedConversationId(), 
     domain: model.chatUrl 
}); 

BotChat.App({ 
     botConnection: botConnection, 
     user: { 
          id: model.userId, 
          name: model.userName, 
     }, 
}, 
window.document.getElementById('chat')); 

botConnection.connectionStatus$ 
.subscribe(function(status){ 
     handleConnection(status) 
}); 

//try to refresh token every 50 seconds
window.setInterval(function (){ 
  console.log("About to refresh token"); 
  $.ajax({ 
     method: "POST", 
     url: "https://directline.botframework.com/v3/directline/tokens/refresh", 
     headers: { 
       "Authorization" : "Bearer " + botConnection.token 
     } 
     }).done(function(result){  
          botConnection = new BotChat.DirectLine({  
               token: result.token,  
               conversationId: getPersistedConversationId(), 
               webSocket: false, 
               domain: model.chatUrl 
          }); 

     BotChat.App({ 
     botConnection: botConnection, 
     user: { 
               id: model.userId, 
               name: model.userName, 
          }, 
     }, 
     window.document.getElementById('chat')); 

     botConnection.connectionStatus$
          .subscribe(function(status){ 
               handleConnection(status) 
          }); 
     }); 
},50000); 

function handleConnection(connectionStatus){ 
     switch(connectionStatus){ 
     case 0: 
          console.log("Uninitialized"); 
          break; 
     case 1: 
          console.log("Connecting"); 
          break; 
     case 2: 
          console.log("Online")
          saveConversationId(botConnection.conversationId);  
          break; 
     case 3: 
          console.log("ExpiredToken"); 
          botConnection = new BotChat.DirectLine({ 
               secret: model.directLineSecret, 
               webSocket: false, 
               conversationId: getPersistedConversationId(), 
               domain: model.chatUrl 
          }); 

          BotChat.App({ 
               botConnection: botConnection, 
               user: { 
                    id: model.userId, 
                    name: model.userName, 
               }, 
          }, 
          window.document.getElementById('chat')); 

          botConnection.connectionStatus$ 
          .subscribe(function(status){ 
               handleConnection(status) 
          });  
          break; 
     case 4: 
          console.log("FailedToConnect"); 
          break; 
     case 5: 
          console.log("Ended"); 
          break; 
     } 
}
```

Token refresh does not throw any error but after mentioned interval Expired token is triggered and even if new connection is created it fires request to refresh endpoint resulting 403 error - this method can be used only with existing token. 

I've looked at the issue https://github.com/Microsoft/BotFramework-WebChat/issues/372

and used c# code to return new conversation object and reconnected, after that message seems to be sent even after timeout however no response from the bot is displayed. 

Can anyone point me to the right direction on how to properly manage token of direct line?

**Comment by billba** [comment]
I don't believe it's true that this only works with WebSockets.

The first question to resolve is why your bot is unable to send messages after 15-30 minutes of inactivity. This shouldn't happen unless you have a connectivity problem, e.g. close your laptop or disconnect from WiFi.

**Comment by billba** [comment]
Since you are using a secret, you should never get an expired token. Is it possible you are passing a token instead of a secret? That would explain the problem.

**Comment by baki32** [comment]
Hi,
thanks for reply, our setup is little bit more complicated - originally we were passing secret however we didn't want that to be exposed on the site so we started using azure API management. Now initial request is made with empty secret to Azure API management that adds secret to authorization header and then forwards to direct line api endpoint. Therefore I need to refresh the token when it expires (ideally I would like to prevent it from expiring in the first place)

**Comment by billba** [comment]
Secrets don't expire.

Tokens do expire, but are automatically renewed by DirectLineJS (unless there's a break in connection). This renewal is enabled by passing { token } when creating DirectLine.

**Comment by baki32** [comment]
Yes I figured, problem was API management after all. Refresh token method was intercepted and authorization header was being replaced with secret instead of token and it was resulting to that 403 error that had bad description (token expired).
