### ISSUE TITLE
Running on Node - Server to Server with Multiple Conversations?

### ISSUE THREAD

**Issue by jblamber** [Microsoft/BotFramework-DirectLineJS#63]
In trying to integrate our own site chat system with the bot framework, without being able to write a custom channel we have tried to use the directline api via a nodejs 'proxy'.

The directlineJS object is obviously designed for client side where one instance = one conversation. Does anyone have a good methodology for proxying multiple conversations? I could build multiple directline objects, each with their own convesationId, but that wouldnt scale very far as multiple polling get/websocket connections would be created to the directline endpoint?

**Comment by billba** [comment]
I would write a custom proxy. The two scenarios are pretty different. For what it's worth, Direct Line isn't a particularly complex protocol, and I've written several such custom channel proxies.
