### ISSUE TITLE
How can I get those Id dynamically from user?? 

### ISSUE THREAD

**Issue by TestUsetGitHubUser** [Microsoft/BotFramework-DirectLineJS#65]
I am using Directline in bot framework but I get always the same user id and name in activity in Message Controller.

    From-id: "default-user"
    From-Name: "User"

How can I get those Id dynamically from user?? 

 

    BotChat.App({
            directLine: { secret: 'xxxx' },
            user: { id: 'userID' ,name = "userName"},
            bot: { id: 'botid' },
            resize: 'detect'
        }, document.getElementById("bot"));

**Comment by billba** [comment]
They are passed in the incoming activity as `activity.from`

**Comment by TestUsetGitHubUser** [comment]
@billba yes I know that now because I was testing from emulator and I didnt get  values until i published it. So can u fix that also in emulator cause its confusing! Please can u tell me is this unique for each user does it work  as sessions and also is this recommended for the production????
Thanks in advance 👍

**Comment by billba** [comment]
Your website specifies the user name & id in the `user` property you pass to BotChat.App. You completely determine what those are. You can generate a unique id/name for everyone - and depend on that in your bot code -- or use the same id/name for everyone and use `conversation.id` for uniqueness. 

There is a version of Emulator coming that will let you test this by specifying user id/name.

**Comment by compulim** [comment]
Close due to inactivity.

If the problem persists, please feel free to comment here, we will reopen the issue. Thanks!
