### ISSUE TITLE
get 403 (Forbidden) after call getSessionId()

### ISSUE THREAD

**Issue by mkovel** [Microsoft/BotFramework-DirectLineJS#71]
Hi, 
i get error in getSessionId() method when i try to use OAuthCard after click by Sign In button

it looks like on screenshot,

![image](https://user-images.githubusercontent.com/911244/39893805-9cdaf0d8-54ad-11e8-829b-45c6206188f5.png)

Also I recieve next response after call getSessionId() 

https://directline.botframework.com/v3/directline/session/getsessionid
```javascript
{
  "error": {
    "code": "ServiceError",
    "message": "Trusted Origin list is empty."
  }
}
```
What am I doing wrong?

Thanks

**Comment by ukphillips** [comment]
I just worked through this issue with the webchat library! How are you initializing the conversation? To solve this I needed to obtain the conversation token by posting the trusted origins:

POST https://directline.botframework.com/v3/directline/tokens/generate

with your master secret as a bearer token and a body of:

{
TrustedOrigins: ["https://URLHOSTINGCLIENTSIDECODE"]
}

**Comment by mkovel** [comment]
Hi, @ukphillips  
1. I've received token throug:
```
POST https://directline.botframework.com/v3/directline/tokens/generate 
Authorization: Bearer ___MY_DIRECTLINE_SECRET___
```

2. And then are creating new DL with received  token
```
new DirectLine({ token: __RECIEVED_TOKEN__,  webSocket: true});
```

Did I answer your question?

**Comment by mkovel** [comment]
@ukphillips  O... I think finaly I understood what you mean. )))
OK i will try your solution tomorrow and give you feedback. 
thanks

**Comment by ukphillips** [comment]
@mkovel sounds like you know what I meant, but just make sure you include the JSON body with the TrustedOrigins property when generating the token. Let me know how it goes!

**Comment by compulim** [comment]
Looks like @ukphillips resolved the issue.

One side note, the `TrustedOrigins` is being moved inside Direct Line channel settings page. You can find more information in this [blog post](https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/).

**Comment by alexknipfer** [comment]
@compulim Is there a way to specify a wildcard as the trusted origin to allow all domains? Configuring it in directline doesn't allow for a `*` as a domain. We allow for our client to embed on pages of their choice, so it would be difficult to maintain the list of trusted origins.
