### ISSUE TITLE
Shutting down websocket connection does not change the connectionStatus

### ISSUE THREAD

**Issue by watadarkstar** [Microsoft/BotFramework-DirectLineJS#75]
#### Description

Shutting down websocket connection does not change the `connectionStatus`. See log below:

`Instabug - REACT LOG: 2018-06-26 21:51:30.489 [info][tid:com.facebook.react.WebSocketExecutor][RCTInspectorPackagerConnection.m:301] Error occurred, shutting down websocket connection: Websocket exception Error Domain=NSPOSIXErrorDomain Code=50 "Network is down" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}`

#### Expected behavior

Connection status reflects this and becomes `ConnectionStatus.FailedToConnect` or attempts to retry if the network is down.

#### Actual behavior 

Connection status remains to be `ConnectionStatus.Connecting`

**Comment by compulim** [comment]
You are correct. We need to revisit error/end/resume/expired conversation on both REST API and Web Socket to make sure they are working as expected.

**Comment by compulim** [comment]
Tracking this issue on #124 (uber-bug on "resume conversation story").

**Comment by masoodyngster** [comment]
2019-06-08 20:58:58.670 [info][tid:com.facebook.react.WebSocketExecutor][RCTInspectorPackagerConnection.m:304] Error occurred, shutting down websocket connection: Websocket exception Error Domain=NSPOSIXErrorDomain Code=50 "Network is down" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}

please help me to resolve this
