### ISSUE TITLE
Handling failures, retrying gracefully, and configuring timeouts and retries

### ISSUE THREAD

**Issue by watadarkstar** [microsoft/BotFramework-DirectLineJS#76]
Hi, I'm a mobile developer who uses DirectLineJS in our React Native application. This issue is going to outline a few topics surrounding failures, retries and configuration questions I have with DirectLineJS. Most of these topics are asking what is recommended or whether the feature exists or if there is an underlying bug. Overall, my intent is to make our app more robust and handle failure more gracefully. And I'm looking for some guidance on these topics.

To prelude, we use Redux + Redux Thunk + React Native + DirectLine in our application. I'm not too familiar with RxJS so bare with me. As I'm learning more about RxJS I'm learning that it may help us solve some of the issues we have below. For example, if we used [redux-observable](https://redux-observable.js.org/) but instead I'm hoping I can chain RxJs functions with DirectLine i.e. `.retries()` and `.delay()` since it uses RxJS or configure DirectLineJS instead of changing our architecture. 

EDIT: As I learn more I think adding redux-observable, redux-sagas, or redux-logic will help us a lot.

### Retries

I use `postActivity` to send messages to the bot, but when the `id` is equal to **"retry"** how should I gracefully handle this case? What does **retry** really mean here? From my understanding, its a recoverable error case and used for token expiration i.e. 403? Code in question:

```javascript
 directLine.postActivity(giftedMessageToBotMessage(message)).subscribe(
    id => {
      if (id === "retry") {
        dispatch(
          messageFailed(message, I18n.t("messageFailedToSend"), "message retry")
        );
        return;
      }
...
```

Image of what this looks like:

![retry-example](https://user-images.githubusercontent.com/3059371/42595655-f29139e4-8520-11e8-93c0-53afc9cf7b75.png)

### Reconnect

Whats the recommended way to handle token expiration? Should I do the following (reconnect when the `connectionStatus` is `ConnectionStatus.ExpiredToken` and what happens if the reconnect fails?):

```
 directLine.connectionStatus$.subscribe(connectionStatus => {
    dispatch(updateConnectionStatus(connectionStatus));
    if (connectionStatus === ConnectionStatus.ExpiredToken) {
      directLine.reconnect(conversation.token);
    }
  });
````

I currently do this but sometimes I get a "retry" `id` from my post activity without the `connectionStatus` changing to `ConnectionStatus.ExpiredToken`, is this a bug? I thought "retry" and `ConnectionStatus.ExpiredToken` are analogous (basically equivalent).

### Configure Timeout

I want to control the timeout of a `postActivity`. Because I want the user to see the failure within a timeout of 10 seconds from sending a simple message (its a better user experience instead of the app hanging). i.e. If the message fails then the user can click the red text below the message to attempt to send the message again. As a naive solution I can use `setTimeout` to check the status of the message, but this is ugly and not very robust. I'm looking for a better solution to configure the timeout of `postActivity` and cancel the subscription. I'm hoping I can do something like this: `directLine.postActivity(message).subscribe(...).timeout(5000).doSomething()`. Is this possible?

![retry-example](https://user-images.githubusercontent.com/3059371/42595655-f29139e4-8520-11e8-93c0-53afc9cf7b75.png)

Naive code example:

```javascript
export function sendMessageToBot(message: GiftedMessage, dispatch: Dispatch) {
let received = false;
  directLine.postActivity(giftedMessageToBotMessage(message)).subscribe(
    id => {
      if (id === "retry") {
        dispatch(
          messageFailed(message, I18n.t("messageFailedToSend"), "message retry")
        );
        return;
      }
     received = true;
      dispatch(updateMessage({ ...message, sent: true, received: true }));
    },
    error => {
      dispatch(messageFailed(message, I18n.t("messageFailedToSend"), error));
    }
  );
  dispatch(updateMessage({ ...message, sent: true }));
 // If we haven't heard from the bot in 10 seconds assume the message failed to send
  setTimeout(() => {
    if (received === false) {
      dispatch(
        messageFailed(message, I18n.t("messageFailedToSend"), "message timeout")
      );
    }
  }, 10000);
}
```

### Configure Retries

Similar to the above, I want to configure the retries for `postActivity`. So something like this: `directLine.postActivity(message).subscribe(...).retries(5)`. Can I do this?

### DirectLine Activity Stream Failure

Listening for messages via the `directLine.activity$` stream is a point of failure in our application. We use `axios` to fetch a token from the server (a point of failure). We then send a message to the bot to let the bot know to start a conversation (a point of failure). We then listen to the activity stream (a point of failure). And all of this we want to retry at an exponential delay. I want to simplify this:

I'm not sure why but we need to **manually send a message to the bot to let the bot know to start a conversation**. In the bot emulator this is not the case, the bot just starts talking. I'm wondering why this might be? 

```javascript
export const listenForMessages = () => async (dispatch: Dispatch) => {
  // Create the conversation which includes the DirectLine token from the server
  const conversation = await createConversation();
  dispatch(updateConversation(conversation));

  // Create DirectLine and send a message to let the bot know we are here
  directLine = await createDirectline(conversation.token);
  dispatch(sendMessages([createJoinMessage()], true));

  directLine.activity$
    .filter(activity => activity.from.id === env.BOT_ID)
    .subscribe((botMessage: BotMessage) => {
      const newMessage: GiftedMessage = botMessageToGiftedMessage(botMessage);
      dispatch(addMessage(newMessage));
    });

  directLine.connectionStatus$.subscribe(connectionStatus => {
    dispatch(updateConnectionStatus(connectionStatus));
    if (connectionStatus === ConnectionStatus.ExpiredToken) {
      reconnect(conversation.token);
    }
  });
};
```

------

@billba Any guidance or recommendations would be greatly appreciated 😄

**Comment by billba** [comment]
Hi @watadarkstar,

I'm excited to hear that you're using DirectLineJS in React Native. I'll try to help as best I can, but I am no longer the person maintaining DLJS. cc: @compulim who might have additional thoughts.

### Retries

First of all, mea culpa for this awkward approach for a return value. One of those things I meant to fix later and never got around to. `retry` is meant to encompass situations where the `post` failed due to issues around connectivity, including token expiration. In this case DLJS doesn't attempt to automatically retry because it doesn't have enough context. You might have just gotten on a plane with no wifi, or entered an underground bunker due to alien invasion, or your personal connectivity is fine but something is broken between the client and your bot.

In Web Chat we leave it up to the user to retry when they think things might be working better.

### Reconnect

As mentioned above, there are other situations where `postActivity` might return "retry", have a look [here](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L573).

If your token has expired then you need to get a new one to pass to `reconnect`. `reconnect` itself doesn't actually do any network operations, it just sets up the token for the next Direct Line operation.

### Configure Timeout

10 seconds is probably too quick for a timeout unless you know your connectivity is excellent and your bot is very quick.

DLJS uses a single timeout value for all operations. [Here](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L520)'s where it's used in `postActivity`.

You can create a customized version to change this value, or to use different timeout values for different operations.

### Configure Retries

Similarly, you'd probably need to create a customized version to add retries to `postActivity`. However see above for reasons why I didn't build in retries in the first place.

### DirectLine Activity Stream Failure

Your bot should get a `conversationUpdate` activity as soon as you call `startConveration`. The only reason you'd need to manually send an activity is if you want to access the user id, which is only sent as part of an activity.

I'm not sure if I agree that subscribing to `activity$` is a point of failure, in that I'm not sure it ever actually fails. I think that in both the websocket and polling cases it will wait forever for messages from the bot, including waiting for you to fix the connection/token as necessary. I'd like to know if this isn't the case.

----

You are pushing on several edges of DLJS, which is great, but it also means you may be experiencing issues that others have not. I'll stay on this thread and try to help out where I can.

**Comment by brandon1780** [comment]
would app id be$ of assistance secret also maybe framwork $build

**Comment by watadarkstar** [comment]
Hi @billba thank you - I appreciate the quick response and in-depth answer 😄. I was hoping I could pick your brain some more. To prelude, I have a chat screen that looks like this:

![37238789_10156516874735120_2302799208840691712_n](https://user-images.githubusercontent.com/3059371/42766804-63afa450-88e9-11e8-99bf-6f64e94e5c31.jpg)

### Connection Issues

As you can see in the above image we display **Connecting with Flyreel...** if the `connectionStatus` is  `ConnectionStatus.Connecting` or `ConnectionStatus.Uninitialized` or `messages.length === 0`.  The problem is: This will "hang" forever if the bot doesn't respond with anything or in other words it will hang until the bot does respond. Which makes our users see a green connecting bar that never goes away. A poor experience which leaves them confused and frustrated that its connecting forever. Hence, we would like to implement a yellow bar that says **"Reconnecting in 5 seconds..."** when we are experiencing problems. However, I'm not really sure if this is possible with the current state of things because I need to be able to control the Directline timeout. And I wonder if the timeout found on this [line of code](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L270) is the heartbeat of the websocket for `directLine.activity$.subscribe` or is it the timeout for `postActivity`? And even if I could control the timeout, how can I make sure I'm in sync with this timeout? And even if I was in sync with the timeout, is it always true that I can recover? Or should I call `directLine.reconnect` within the interval of my own timer?

Some more context for you, the reason we wouldn't be receiving messages from the bot is the follow (I have bolded the error cases we are trying to catch):

- The token API is down or errors out. (We currently catch this case and display "The service failed to connect, retrying connection..." in the bar above but still need to handle the reconnection part)
- The network is down. (We catch this case using [NetInfo](https://facebook.github.io/react-native/docs/netinfo.html) and display "Sorry, your device seems to be offline. Please reconnect to continue." in the bar above)
- The network is slow. (**We do NOT catch this case but need to and its what I'm addressing above**)
- The bot is down. (**As far as I know we might be catching this case, the token API and the bot API are different so the token could succeed but the bot could fail. If the bot fails I understand that Directline will get into the "retry" case or the error case and we would catch these errors**) 
- The server is miss-configured and is using the wrong directline secret. (**We do not catch this case, directline does not fail and I don't think it knows it should fail**)

Here's a code snippet of what we are doing:
```
 // Create the conversation which includes the DirectLine token from the server
  let conversation;
  try {
    conversation = await createConversation();
  } catch (e) {
    dispatch(updateConnectionStatus(ConnectionStatus.FailedToConnect));
    return;
  }
  dispatch(updateConversation(conversation));

  // Create DirectLine with the conversation token from the server
  directLine = await createDirectline(conversation.token);

  // Subscribe to the bot message activity stream
  directLine.activity$
    .filter(activity => activity.from.id === env.BOT_ID)
    .subscribe((botMessage: BotMessage) => {
      const newMessage: GiftedMessage = botMessageToGiftedMessage(botMessage);
      dispatch(addMessage(newMessage));
    });

 // Subscribe to DirectLine's connection status stream
  directLine.connectionStatus$.subscribe(connectionStatus => {
    Logger.connectionStatus(connectionStatus);
    dispatch(updateConnectionStatus(connectionStatus));

    // Token expired we need to reconnect by refreshing the token
    if (connectionStatus === ConnectionStatus.ExpiredToken) {
      try {
        reconnect(conversation.token);
      } catch (e) {
        dispatch(updateConnectionStatus(ConnectionStatus.FailedToConnect));
      }
    }
  });
``` 

### Multiple Conversations and Resuming Conversations

Bare with me as I'm still trying to figure out this part and have a lot of questions regarding resuming conversations and multiple conversations.

Our app actually **will** have many conversations. To give some context its an insurance app and each insurance inspection is a different conversation. So when you enter our app you might see a list of existing inspections, each inspection is tied to one conversation. What I can't wrap my head around is... Can I tie these conversations to the DirectLine conversations provided by my token API (I think so based on what it says in the [README](https://github.com/Microsoft/BotFramework-DirectLineJS#resume-an-existing-conversation))? And should DirectLine be some global instance or some local instance tied to a specific conversation / inspection?  In other words how do I handle multiple conversations and resume conversations with DirectLine? 

More context: Every time a user opens a new conversation / inspection in our app, the token API generates a new token and gives me a new conversation object and we do `new Directline({ token })`. But this feels weird because I might want to resume a conversation. I don't want to generate a new conversation all the time, I want to resume an old conversation. Which makes me think, should my token API supply a persisted token and I call `directline.reconnect({ token })` to resume the conversation? And should I make Directline global so the whole app uses one directline instance? And how should I resume a conversation and rehydrate my application, through Directline or some REST API prior to connecting to Directline?

**Comment by watadarkstar** [comment]
### Connection Issues (Cont'd)

I ended up experimenting with redux-saga to monitor connection issues within the network. Since **DirectLine** doesn't really give us access to the timeout I made the message generic: **The service failed to connect, retrying connection...** - but it would be nice if we could control the reconnection interval / heartbeat.

The code does a variety of things like monitoring network changes (offline), monitoring directline's connection status and watching if we have never got any messages from the bot:

```javascript
networkListener = () => {
    NetInfo.getConnectionInfo().then((connectionInfo: ConnectionInfo) => {
      this.setState({ connectionInfo, show: true });
    });
    NetInfo.addEventListener(
      "connectionChange",
      this.handleFirstConnectivityChange
    );
  };
...
function* listenForMessages() {
  // watch if we haven't got any messages from the bot, let the user know we failed and are trying to reconnect
  yield fork(watchMessages);

  // Create the conversation which includes the DirectLine token from the server
  let conversation;
  try {
    conversation = yield call(createConversation);
  } catch (e) {
    yield put(updateConnectionStatus(ConnectionStatus.FailedToConnect));
    return;
  }
  yield put(updateConversation(conversation));

  // Create DirectLine with the conversation token from the server
  const directLine = yield call(createDirectline, conversation.token);
  yield put(updateDirectLine(directLine));

  // Watch DirectLine's connection status stream
  yield fork(watchConnectionStatus);

  // Logs for debugging
  console.info("conversation", conversation);

  // Create a bot activity / message channel to subscribe to incoming bot messages
  const channel = yield call(createBotActivityChannel, directLine);
  while (true) {
    const botMessage: BotMessage = yield take(channel);
    const newMessage: GiftedMessage = botMessageToGiftedMessage(botMessage);
    yield put(addMessage(newMessage));
  }
}
```

![37310284_10156522813045120_7781966838925099008_n](https://user-images.githubusercontent.com/3059371/42892788-b15d9520-8a80-11e8-84e3-6e2303a934f7.jpg)

**Comment by watadarkstar** [comment]
@billba:

> I'm not sure if I agree that subscribing to activity$ is a point of failure, in that I'm not sure it ever actually fails. I think that in both the websocket and polling cases it will wait forever for messages from the bot, including waiting for you to fix the connection/token as necessary. I'd like to know if this isn't the case.

The activity stream doesn't fail directly, but the bot API could fail and we would never know why. For example, in our app the bot must say something before the user can do anything. So if the bot fails to respond, we would never know. To workaround this I have a watcher that watches `messages.length === 0` like so:

```javascript
/*
     Worker Sagas
*/
function* messagesCheck() {
  // get the chat state
  const chat = yield select(getChat);

  // if we haven't got any messages from the bot let the user know we failed and are trying to reconnect
  if (chat.messages.length === 0) {
    yield put(updateConnectionStatus("retry"));
  }
}

/*
      Watcher Sagas
*/
function* watchMessages() {
  while (true) {
    // after 10 seconds or so check if we have received any messages from the bot
    yield delay(TIMEOUT);
    yield call(messagesCheck);
  }
}
```

**Comment by billba** [comment]
You also may want to look at redux-observable which is like redux-saga but implemented with observables via rxjs. That's what Web Chat uses. I've found it to be very very clean.

**Comment by watadarkstar** [comment]
@billba @compulim Hi Bill quick question, as I'm testing token reconnection with directline, I need to know if `directLine.reconnect(conversation)` needs to be called before or after the expiry timeout or it doesn't matter?

**Comment by billba** [comment]
@watadarkstar I think you're conflating the act of getting a new token from Direct Line, which is not handled by this library, with giving that token to the DirectLineJS object to use in subsequent calls.

Typically getting a new token is handled by your website, which holds the Direct Line secret used to obtain it. 

Obviously you cannot get a new token if the network is down. You will have to manage that yourself.

**Comment by watadarkstar** [comment]
@billba Hi Bill, I think I understand better now but I'm still confused and I think I need to clarify my question better.

So when I call `new DirectLine({ token })` my back-end calls Direct Line **/generate** to get the token like so:

```
POST https://directline.botframework.com/v3/directline/tokens/generate
Authorization: Bearer SECRET
```

Then when the connection status becomes `ConnectionStatus.ExpiredToken` my back-end should call which end point? I think this is where I'm confused. I am currently calling **/refresh**:

```
POST https://directline.botframework.com/v3/directline/tokens/refresh
Authorization: Bearer TOKEN_TO_BE_REFRESHED
```

But based on what you said I think I should be calling **/conversations/{conversationId}**:

```
GET https://directline.botframework.com/v3/directline/conversations/{conversationId}?watermark={watermark_value}
Authorization: Bearer SECRET_OR_TOKEN
```

Is that correct? My confusion is with which endpoint should I be calling when the connection status is `ConnectionStatus.ExpiredToken`. Based on the README, I'm suppose to call the Reconnect API but its unclear as to what that is.

> If your app created your DirectLine object by passing a token, DirectLine will refresh that token every 15 minutes. Should your client lose connectivity (e.g. close laptop, fail to pay Internet access bill, go under a tunnel), connectionStatus$ will change to ConnectionStatus.ExpiredToken. Your app can request a new token from its server, which should call the Reconnect API. The resultant Conversation object can then be passed by the app to DirectLine, which will

**Comment by billba** [comment]
Correct, when you have an expired token your backend server should be calling `/conversations/{conversationId}`, using the secret it holds.

**Comment by watadarkstar** [comment]
Thanks @billba this makes so much more sense now. You rock! 🙌

**Comment by billba** [comment]
I cannot tell a lie; I do rock.

**Comment by Nandha29** [comment]
Hi, I'm still occasionally encountering this `retry` issue. Could you please help me resolve it? Thanks in advance!![Image](https://github.com/user-attachments/assets/6bf5c08e-ceca-4ebd-a274-8ec5cddf7b12)
