### ISSUE TITLE
Direct Line JS: Backoff on 429, stop on 404, and relax on 400

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-DirectLineJS#90]
We should implement backoff and error handling logic correctly.

- 429, we will backoff
- 404 (bot is gone), we will stop
- 400 (something wrong on client request), we will backoff

**Comment by corinagum** [comment]
Check the following:
- Start conversation (`startConversation`)
   - Poll by REST API (`pollingGetActivity`)
   - Web Socket connection
      - Get stream URL (`reconnectToConversation`)
      - Upgrade call (`observableWebSocket`)
- Post activity (`postActivity`)

**Comment by compulim** [comment]
Tracking this issue on #124 (uber-bug on "resume conversation story").
